### ISSUE TITLE
Provide Better Error Support for Missing Environment Deploy Config

### ISSUE THREAD

**Issue by danshultz** [ember-cli/ember-cli-deploy#101]
The default build environment is `development` and if you run an `ember deploy` without specifying the build environment it can provide confusion as most will not have a config for `development`. Additionally, the error for a missing environment section is a nondescript null error. 

When I run a deploy for an environment for which no config section exists
Then an error should inform me that my config section for `<environment>` is missing.

**Comment by achambers** [comment]
:+1:
