### ISSUE TITLE
Include Reasonable S3 CORS Defaults

### ISSUE THREAD

**Issue by danshultz** [ember-cli/ember-cli-deploy#103]
Add details to the README to help people configure the CORS support for hosting their assets on S3.

**Comment by achambers** [comment]
Does this sort of thing make more sense in the actual S3 plugin?

**Comment by samselikoff** [comment]
Definitely think this belongs in the plugin. We can have some portions of the docs site for the most common plugins.

**Comment by lukemelia** [comment]
Closing in favor of issue opened on s3 plugin.
