### ISSUE TITLE
Provide Documentation or a Plugin to Help with S3 setup

### ISSUE THREAD

**Issue by danshultz** [ember-cli/ember-cli-deploy#104]
In order to help setup of s3 buckets and help guide people newer to s3 and hosting their assets there, it may be helpful to include some recommended S3 bucket configurations in a wiki page or even create a plugin or hook to configure s3 buckets.

**Comment by rtm** [comment]
Is there some configuration required other than creating the bucket?

**Comment by achambers** [comment]
@rtm, you will need the accessKeyId, secretAccessKey and region as well.
Please look at the example deploy.js in the README

**Comment by jessiahr** [comment]
Following the instructions in the readme for using s3 I have not been able to get a working deploy. Once the `ember deploy` command is done I can see the uploads in the bucket but when I test the url I get:

    GET http://somebucket.s3.amazonaws.com/assets/gutenberg-32141d944c8deb502c68a32ad22a9e4b.css net::ERR_CONTENT_DECODING_FAILED
    GET http://somebucket.s3.amazonaws.com/assets/gutenberg-23d50de23068d7b0c5915070c9e5a051.js net::ERR_CONTENT_DECODING_FAILED
    GET http://somebucket.s3.amazonaws.com/assets/vendor-b801da685e73674bd55b88ad90f1be54.js net::ERR_CONTENT_DECODING_FAILED 

@achambers you mentioned needing a region but where in the deploy.js does that get set? Also is there a bucket policy required for this to work?

**Comment by IanVS** [comment]
+1 for a little more help on the S3 side.  @achambers, I'm fine with providing a key and secret (and region), but what permissions does the user associated with that key need?  For example, to upload code to a certain bucket, I have a policy for a user like so:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:PutObject"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:s3:::bucketname/*"
        }
    ]
}
```

Are there any other actions required as well for this to work?

**Comment by LevelbossMike** [comment]
@IanVS 

A Policy like this should work:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": ["s3:ListAllMyBuckets"],
      "Resource": "arn:aws:s3:::*"
    },
    {
      "Effect": "Allow",
      "Action": "s3:*",
      "Resource": [
        "arn:aws:s3:::<bucket-name>",
        "arn:aws:s3:::<bucket-name>*"
      ]
    }
  ]
}
```

The list all buckets action of course isn't necessary you can restrict this to the respective bucket of course.

**Comment by ryanjm** [comment]
@LevelbossMike - It doesn't seem like full actions should be allowed. Shouldn't there be a safe subset?

**Comment by LevelbossMike** [comment]
@ryanjm Not sure what you want to restrict in an asset bucket / index bucket. You can try out to disable deletion of bucket contents for example but you are already granting rights for the user to "deploy" your app so I don't think that would make that much of a difference.

**Comment by ryanjm** [comment]
@LevelbossMike That's a good point. I guess these credentials shouldn't be living anywhere except on a trusted computer.

**Comment by IanVS** [comment]
@ryanjm Ideally credentials should live in an environment variable, to maintain separation between config and code.  See http://12factor.net/config (written by engineers at Heroku) for a good explanation.

**Comment by kriswill** [comment]
:+1: on Twelve-Factor configuration.

**Comment by kriswill** [comment]
Twelve-Factor mostly refers to deployed apps, like configuring instances of docker containers with db connection strings, cipher keys, etc.  But it wouldn't be that difficult to use something like https://github.com/motdotla/dotenv to get similar benefits at dev-time.

**Comment by ryanjm** [comment]
Right, I’m using dotenv to keep my credentials local. That’s what I meant by keeping them on a local machine. Those will never be published to a server so I don’t need to worry as much about what access they have.

**Comment by lukemelia** [comment]
dotEnv file support is baked into 0.5, and S3 config is documented in https://github.com/ember-cli-deploy/ember-cli-deploy-s3/blob/master/README.md. Closing.
