### ISSUE TITLE
Create a Jekyll site for docs

### ISSUE THREAD

**Issue by samselikoff** [ember-cli/ember-cli-deploy#106]

**Comment by lukemelia** [comment]
We would like to recommend people visit this site after installing via `ember install:addon ember-cli-deploy`.

The site should feature a list of Supported and Community plugins with a short explanation on each, command to install it, and link to the repo.

The site should be easily PR-able so that new plugin authors can get their plugins listed.

**Comment by lukemelia** [comment]
We may also want a section listing "Server solutions that work with ember-cli-deploy "

**Comment by samselikoff** [comment]
absolutely. hoping to start this soon

**Comment by blimmer** [comment]
@samselikoff did you have time to get this started? I could help out here, [my blog](http://benlimmer.com) is a Jekyll blog so I could get us started, at least.

**Comment by samselikoff** [comment]
I did but barely, let me touch it up a bit and push it to `gh-pages`. Hopefully today.

**Comment by samselikoff** [comment]
K I kicked it off: https://github.com/ember-cli/ember-cli-deploy/tree/gh-pages

If you develop be sure to mobile-first :)

**Comment by blimmer** [comment]
I was looking at starting to tackle this, but with the big pipeline changes coming in 0.5.0 I think it might make sense to wait until this milestone is farther along.

**Comment by samselikoff** [comment]
I was planning on versioning the api docs, `/api/v0.4.2` or something. There should also be some high-level sections on explaining what the project does and why its needed. Also the plugins.

If you don't have time, no worries :) I'm planning on working on the content soon

**Comment by lukemelia** [comment]
This has been signed, sealed, delivered.
