### ISSUE TITLE
Support/document running multiple versions in parallel

### ISSUE THREAD

**Issue by treyhunner** [ember-cli/ember-cli-deploy#107]
I believe this feature is already supported, but I have only found it to work with hash URLs so far.  If this feature will be officially supported, it would be great to document the abilities/limitations.

**Comment by achambers** [comment]
Hi @treyhunner .  Could elaborate on the problem a little more please?

**Comment by samselikoff** [comment]
Are you talking about the `/your-app?index_key=build_id` that fetches different builds in your production environment?

**Comment by blimmer** [comment]
If I understand @treyhunner correctly, this is actually something we've considered doing as well. It would be great for an A/B testing setup where you wanted to test an entirely new design, but perhaps have your app server choose to serve up the new design to 1/10 people.

**Comment by samselikoff** [comment]
@blimmer this is absolutely the sort of thing that will be possible with deploy pipelines using ember-cli-deploy. Ultimately your backend is responsible for deciding which index file to server, but plugin authors could expose new commands that let you set some of these values, e.g. which percentage to serve which build. I don't believe this would be part of core - we're trying to keep the core concepts things that apply to nearly all deploy setups.

**Comment by blimmer** [comment]
That definitely makes sense and I agree that a plugin should handle this sort of behavior. We're very excited to be able to use this kind of functionality!

**Comment by treyhunner** [comment]
Sorry for not being clear enough.  I didn't mean to create the issue and disappear.

By simple guessing, I found this seems to work: https://freemusic.ninja/freemusicninja:cded58b.html#/resources

A `/your_app?index_key=build_id` format would be great.  I assume S3/nginx/etc. would need to be configured to serve files appropriately based on the build ID.

**Comment by achambers** [comment]
I'm not sure I am clear on what the problem is.  Are you saying you'd like to be able to view two different builds of the app via passing in a query param?

If so, then by using a combination of [ember-deploy-redis](https://github.com/LevelbossMike/ember-deploy-redis) and [philipheinser/ember-lightning](https://github.com/philipheinser/ember-lightning) you should be able to accomplish this now.

Does that help?

Also, I'm not quite sure what you meant by:

>  I have only found it to work with hash URLs so far

**Comment by treyhunner** [comment]
@achambers I meant my method for manually viewing the tag for a particular file like this: https://freemusic.ninja/freemusicninja:cded58b.html#/resources

Using a query param would be great, but I don't care which method is used so long as it works.  I would like to continue to deploy to my existing server and preferably (though not necessarily) continue to serve my pages through nginx or Apache.

**Comment by lukemelia** [comment]
This is going to vary by plugin and hosting environments, so it's not actionable here.
