### ISSUE TITLE
eu-west S3 bucket configuration

### ISSUE THREAD

**Issue by petrjanda** [ember-cli/ember-cli-deploy#109]
After first try to deploy to eu-west s3 bucket it didn't work and error message wasn't particularly helpful. I would see just the following log output and the app would hang forever.

```
ember deploy --environment production
version: 0.1.15
Could not find watchman, falling back to NodeWatcher for file system events
Built project successfully. Stored in "dist/".
Uploading assets...
Uploading: charts-d01933e99231f3f60ba6af04df5bb3f7.js
Uploading: charts-d5d8b9e0324ab53533eff47dbbdc7632.css
Uploading: charts.map
Uploading: vendor.map
Uploading: crossdomain.xml
Uploading: icon.ico
Uploading: index.html
Uploading: robots.txt
```

I've figured out its because the upload is by default done to US bucket. Eventually the solution is simple - just adding region to assets config as so:

```
  staging: {
    buildEnv: 'staging',
    store: {
      ...
    },
    assets: {
      ...
      bucket: 'gwi-s-fe',
      region: 'eu-west-1'
    }
  }
```

May be worth adding to docs or improving the log output?

**Comment by joebartels** [comment]
good point. sounds like this is in same realm as this issue on ember-cli-s3? https://github.com/LevelbossMike/ember-deploy-s3/issues/4

**Comment by LevelbossMike** [comment]
Thanks for this issue!

I agree this should be added to the docs because the error message you get from aws is not really helpful.

https://github.com/LevelbossMike/ember-deploy-s3/issues/5

I am closing this here in favor of the issue in the ember-deploy-s3-repo.

**Comment by petrjanda** [comment]
Cheers!
