### ISSUE TITLE
Confusing naming and upgrade path for ember-deploy

### ISSUE THREAD

**Issue by kenips** [ember-cli/ember-cli-deploy#111]
Guys, great job merging all deploy projects and releasing 0.4! Just want to some give feedback on the release:

1. Naming is still confusing especially the adapters still have `ember-deploy-` prefix not `ember-cli-deploy`. I hope that this can be added as a requirement for 0.5.0 adapters? Thanks!

2. I don't check this page nor npmjs.org for updates but I run `npm outdated ---depth=0`. Being currently on `ember-deploy` I'd not be able to discover ember-cli-deploy 0.4.x. I wonder if whoever has `ember-deploy` access could push a 0.3.2 with a deprecation message on start? That'd be wonderful for those who're on `ember-deploy`.

Thanks for the awesome work again!

**Comment by lukemelia** [comment]
Point number 1 is indeed a requirement for 0.5.0 plugins, and an `ember-cli-deploy-plugin` keyword is required as well.

@LevelbossMike is feedback point 2 above done? can we close out this issue?

**Comment by LevelbossMike** [comment]
I'll try to push a new version of ember-deploy tomorrow @lukemelia

**Comment by LevelbossMike** [comment]
npm will now print out a deprecation message when installing `ember-deploy`
