### ISSUE TITLE
Why specify gzip to adapters when there is ember-cli-gzip

### ISSUE THREAD

**Issue by archit** [ember-cli/ember-cli-deploy#122]
I noticed this while testing [ember-deploy-s3](https://github.com/LevelbossMike/ember-deploy-s3); which btw doesn't really compress the assets if I set `gzip: true`. 

Anyway, I was wondering if we should just remove the responsibility of zipping the assets from ember-cli-deploy-* addons, and leave it to ember-cli-gzip.

**Comment by LevelbossMike** [comment]
Hi @archit!

Thanks for this issue. I had a look at ember-cli-gzip when developing the first version of this addon and frankly can't remember anymore why I decided against using it but I'll look into it again.

Can you please provide more info about you mentioning problems with ember-cli-deploy not gzipping assets correctly? It is working in my projects with default settings and should also if you provided a assets config like this:

```
// config.js

module.exports = {
    // ...
    assets: {
      type: 's3', // default asset-adapter is 's3'
      gzip: false, // if undefined or set to true, files are gziped
      gzipExtensions: ['js', 'css', 'svg'], // if undefined, js, css & svg files are gziped
      accessKeyId: '<your-access-key-goes-here>',
      secretAccessKey: process.env['AWS_ACCESS_KEY'],
      bucket: '<your-bucket-name>'
    }
}
```
You can see the defaults [here](https://github.com/ember-cli/ember-cli-deploy/blob/702d0d4a03fef9ffbcc5a1b318cbf2512af31197/lib/models/config.js#L44). As you can see you shouldn't need to provide a gzip-option if you want assets to be gzipped but it shouldn't hurt if you did.

**Comment by lukemelia** [comment]
For 0.5.0, we will split these responsibilities between ember-cli-deploy-gzip and ember-cli-deploy-s3.

**Comment by lukemelia** [comment]
Happy to reopen if there is a bug in the current ember-deploy-s3 that needs to be addressed.
