### ISSUE TITLE
Expires Header

### ISSUE THREAD

**Issue by enspandi** [ember-cli/ember-cli-deploy#126]
Would it make sense to add an expires header (1 year?) to prevent the 304 Not Modified calls? Just a minor performance improvement in general, but for many assets this could be worth it, since the browser saves a whole round trip for each asset (especially on mobile).

Looking for "200 OK (from cache)" instead of "304 Not Modified" to see in the developer tools.

**Comment by achambers** [comment]
Hi @enspandi. Which files are you thinking this would be for? Also, it's not really an issue for ember-cli-deploy. I assume it's the ember-deploy-redis or ember-deploy-s3 plugins you're talking about. 

In which case, the issue should really be raised on the respective repo.

**Comment by LevelbossMike** [comment]
Closing in favor of https://github.com/LevelbossMike/ember-deploy-s3/issues/7
