### ISSUE TITLE
APP_NAME.js is trying to be retrieved from the node server that is serving up index.html from redis

### ISSUE THREAD

**Issue by rtm** [ember-cli/ember-cli-deploy#131]
I've run `ember deploy`. Since my back-end is a node-app I followed the guidance in the `ember-lightning` repo.

Problem is, the index.html that is in redis and is served up by the logic in my node server refers simply to `assets/frontend.js`, for example (frontend is the name of my app). I would have thought that it should have been rewritten to refer to S3; or that the `<base>` tag should have been set to the appropriate S3 URL; right now it is just `/`. The request for `frontend.js` comes back to my server of course, which has no way to serve it up.

What am I missing?

**Comment by achambers** [comment]
Hi @rtm . I'd say what you're missing is that, in your Brocfile, you need to tell the fingerprinting task to prepend the s3 url to your assets. It's all there in the README. Have a look and if you have any other problems just ask. I'm going to close this issue. We can reopen of this doesn't fix it.
