### ISSUE TITLE
S3 content-type is set to gzip even if file is not gzipped

### ISSUE THREAD

**Issue by rtm** [ember-cli/ember-cli-deploy#132]
It seems that when gzip is set to false, the file is correctly loaded unzipped to S3, but the S3 content-type is still set to gzip, which causes an encoding error when downloading.

**Comment by achambers** [comment]
Thanks for this @rtm

**Comment by bradplank** [comment]
Looks like response-header overrides may need to be used when uploading the content to S3: `response-content-type=<content-type>`

**Comment by tim-evans** [comment]
@rtm this was a bug in ember-deploy-s3. The fix was merged, but not released. ping @LevelbossMike

**Comment by LevelbossMike** [comment]
@tim-evans thx for the ping. I just release version 0.0.4 to npm.
