### ISSUE TITLE
Not working with iojs

### ISSUE THREAD

**Issue by courthead** [ember-cli/ember-cli-deploy#133]
I created a new Ember CLI project, a new bucket on S3, and followed the instructions on the README to npm install ember-cli-deploy, ember-deploy-redis, and ember-deploy-s3. I also created `config/deploy.js` that's basically a copy of what's in the README. However, when I run `ember deploy` or `ember deploy --environment=development` it gets to this point and then freezes up and never recovers:

    $ ember deploy --environment=development
    version: 0.2.3
    Built project successfully. Stored in "dist/".

This happened with iojs v1.6.3. I upgraded to iojs v1.8.1 and this was still occurring. When I switch to node v0.12.2, however, things work fine.

Also, I tested the individual commands, and `ember deploy:index` works fine when I'm using iojs, but `ember deploy:assets` freezes up, so I'm guessing this might have to do with the s3 adapter?

EDIT: We might want to add a note to the README about this until it's fixed. It's definitely frustrating to run into when you're just getting started.

**Comment by achambers** [comment]
Thanks for the heads up @courthead .

@cibernox, is this similar to what you were experiencing?

**Comment by cibernox** [comment]
@achambers Yes, those are exactly my symptoms. I haven't deployed on the last 2 weeks though.

**Comment by Jellyfishboy** [comment]
I'm also having issue deploying my assets to S3. The deployment hangs during the uploading of the assets.

Node v.0.12.2

**Comment by deivinsontejeda** [comment]
Same issue, I did some debug and I've found on this function  [copyToOutputPath](https://github.com/ember-cli/ember-cli-deploy/blob/master/lib/tasks/assets.js#L89-L100) the execution is stopping without any error. I did put the callback in order to see if there is any error and the callback never is called.


```javascript
   return ncp(inputPath, outputPath, {
      dereference: true,
      clobber: true,
      stopOnErr: true,
      limit: 2
    }, function(err){ console.log(err) });
```

**Comment by LevelbossMike** [comment]
@Jellyfishboy ist this really an issue with node 0.12.2? I was using node 0.12.2 on my codementor session and it worked fine.

I was using node 0.12.2 via nvm.

**Comment by deivinsontejeda** [comment]
The issue is with iojs.

**Comment by LevelbossMike** [comment]
yes I am experiencing this too with io.js but @Jellyfishboy was talking about node 0.12.2 which I can't reproduce.

I'll look into the iojs hanging issue most likely the s3 library I am using in ember-deploy-s3 is to blame.

**Comment by Jellyfishboy** [comment]
I'm no longer having issues with the 'Uploading assets...' for node v0.12.2. Strange, thanks though.

**Comment by truenorth** [comment]
Confirming that both iojs 1.8.1 and 2.0.2 hang on asset uploading. It seems to publish the index file to redis successfully

**Comment by IanVS** [comment]
I just hit this as well with iojs.  100% CPU usage by ember.

**Comment by trucam** [comment]
Bump 

```
Uploading: fontawesome-webfont.svg
Uploading: fontawesome-webfont.ttf
Uploading: fontawesome-webfont.woff
Uploading: fontawesome-webfont.woff2
Uploading: index.html
Uploading: robots.txt
```

happens with nodejs 0.12.4 (brew), no nvm. Uploads to S3 no problem though.
