### ISSUE TITLE
Change ownership of default adapters to ember-cli organization

### ISSUE THREAD

**Issue by tim-evans** [ember-cli/ember-cli-deploy#136]
Since `ember-deploy-redis` and `ember-deploy-s3` are the out-of-box defaults, I feel like it makes most sense for them to live in the ember-cli organization.

Any thoughts on this?

**Comment by achambers** [comment]
Hi @tim-evans . We have had a very brief discussion about this a few months back but I don't believe we decided upon a way forward.  We do totally agree that there should be some easy way for users to see a list of *supported* or endorsed plugins but we haven't decided the best way for this to be surfaced yet.  Not convinced if them being put under the ember-cli org is necessarily the way to go.

Ideally we want the community to be building plugins and we will compile a list somewhere of the ones we endorse and tests ember-cli-deploy against.

We are in the process of putting together a static site as a landing place for ember-cli-deploy which will include this list.

Thanks for the input. More than happy to get this discussion going here.  Love to hear the thoughts of @lukemelia , @samselikoff , @LevelbossMike and @danshultz

**Comment by tim-evans** [comment]
@achambers Thanks for the quick response. Yeah, that makes sense to me. Maybe getting in touch with @kategengler about adding an "endorsed" flag to emberobserver.com? That seems like the happiest path going forward

**Comment by achambers** [comment]
Yep, that could also be an option :)

**Comment by LevelbossMike** [comment]
The endorsed flags sounds like a better idea than moving a lot of plugins to the ember-cli organization as far as I am concerned because this might get out of hand pretty quickly I suppose. Happy to accept more contributors to the above mentioned projects though :)

**Comment by kategengler** [comment]
Right now on emberobserver there is a flag for "Official" that is set for anything under the emberjs or ember-cli organizations. My reasoning was that anything under those orgs has the support, maintenance, and the eyes of the core team. For an "endorsed" flag, I would need a way of getting a list of addons that are in that set, and who exactly is endorsing them.

**Comment by lukemelia** [comment]
Maybe we could drive this out of `package.json`.

```js
...
  "ember-addon": {
    "worksWellWith": ['ember-deploy-s3', 'ember-deploy-redis', 'ember-deploy-etc']
  }
...
```

**Comment by tim-evans** [comment]
I like the approach of 'works-well-with'.

**Comment by tim-evans** [comment]
I think this no longer belongs here. If anyone wants, they may close this issue and submit an RFC for the `works-well-with` note.

**Comment by achambers** [comment]
Thanks @tim-evans .  I have captured the `works-well-with` change in our task list for in the v0.5.0 PR #130
