### ISSUE TITLE
Uploading Hidden Files

### ISSUE THREAD

**Issue by jherdman** [ember-cli/ember-cli-deploy#138]
I updated ember-cli today to 0.2.5. Upon deploying to a staging box, I noticed the following:

```
Built project successfully. Stored in "dist/".
Uploading assets...
Uploading: .DS_Store
Uploading: ._
Uploading: .DS_Store
Uploading: ._
Uploading: .DS_Store
Uploading: ._
```

This doesn't seem right to me. I noticed on https://github.com/ember-cli/ember-cli-deploy/issues/11#issuecomment-62206031 that a suggestion was made to ignore hidden files by default, but no clear follow up was made (as far as I can tell).

How does one go about ensuring these sorts of files aren't uploaded?

**Comment by lukemelia** [comment]
Thanks for bringing this up @jherdman!
