### ISSUE TITLE
Struggling to deploy to production

### ISSUE THREAD

**Issue by ianpetzer** [ember-cli/ember-cli-deploy#145]
Hi,

I'm struggling to deploy my index file to my production. I can successfully deploy to the Redis on my local machine but whenever I run ember deploy --environment production it appears to ignore the Redis that I have configured for production and deploy against my locally running Redis.

I have included my deploy.js config file below.

I am confident that it is reading in the production assets configuration. When I change the s3 settings for production, the deploy process picks them up,

However, all my attempts to specify a Redis server are ignored and if I shut down the Redis on my local machine and try ember deploy --environment production then I get the following error:

     Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED

This is the deploy.js I'm using.

Many thanks for any help.

    module.exports = {
      development: {
        buildEnv: 'production', // Override the environment passed to the ember asset build. Defaults to 'production'
        store: {
          type: 'redis', // the default store is 'redis'
          host: 'localhost',
          port: 6379
        },
        assets: {
          type: 's3', // default asset-adapter is 's3'
          gzip: false, // if undefined or set to true, files are gziped
          gzipExtensions: ['js', 'css', 'svg'], // if undefined, js, css & svg files are gziped
          exclude: ['.DS_Store', '*-test.js'], // defaults to empty array
          accessKeyId: "MY_ID",
          secretAccessKey: "MY_KEY",
          bucket: "MY-BUCKET"
        }
      },

      production: {
        store: {
          host: "MY_HOST",
          port: 16344,
          password: "MY_PASS"
        },
        assets: {
          accessKeyId: "MY_ID",
          secretAccessKey: "MY_KEY",
          bucket: "MY_BUCKET"
        }
      }
    };

**Comment by blimmer** [comment]
That definitely should work. are the assets going into the bucket defined in the `production` block? Or is it just ignoring everything?

Also, I got your S3 secrets in my email. I see you've edited them here, but you should revoke that key.

**Comment by ianpetzer** [comment]
Thanks @blimmer, I've cancelled the key.

I can confirm that the assets settings for the production environment are being used correctly. I can set different buckets for development / production environments and deploy into them accordingly.

It just seems to ignore the production store settings and deploys to the Redis on my local machine.

I've checked the production credentials in my Rails terminal and they are correct.

**Comment by LevelbossMike** [comment]
This is most likely an issue with ember-deploy-redis. I will push a fix (version 0.0.4) in the next minutes. Right now you can use version 0.0.2 or current master of ember-deploy-redis.

**Comment by LevelbossMike** [comment]
sorry for the inconvenience caused. The tests didn't find this issue.

**Comment by ianpetzer** [comment]
Oh amazing! Thanks so much @LevelbossMike 

Such a great project!!

**Comment by LevelbossMike** [comment]
ember-deploy-redis@0.0.4 should be up on npm. Can you confirm this fixes your issue? @ianpetzer

**Comment by LevelbossMike** [comment]
I have just unpublished version 0.0.3 ember-deploy-redis from npm as it contains this quite serious bug.

**Comment by ianpetzer** [comment]
@LevelbossMike Thanks so much.. I can confirm that ember-deploy-redis@0.0.4 has fixed the issue

**Comment by LevelbossMike** [comment]
Great to hear! Have fun deploying your apps :)

**Comment by ianpetzer** [comment]
Thanks!
