### ISSUE TITLE
Status with 0.5.0?

### ISSUE THREAD

**Issue by thehydroimpulse** [ember-cli/ember-cli-deploy#147]
Seems like the project has stalled a little bit after being merged together. Are you guys still working on this release?

**Comment by achambers** [comment]
Indeed we are @thehydroimpulse .  You can see what we're doing on [this PR](https://github.com/ember-cli/ember-cli-deploy/pull/130).  There is quite a bit to do still but we are chugging away. Feel free to chip in ;)

**Comment by thehydroimpulse** [comment]
Thanks @achambers! I'll definitely dig into things.
