### ISSUE TITLE
Demo application

### ISSUE THREAD

**Issue by ghedamat** [ember-cli/ember-cli-deploy#148]
Hi,

first of all thanks for this amazing project! :)

I've recently put together a demo application for our Toronto meetup that shows a way to implement the ember-deploy strategy with redis

https://github.com/ghedamat/ember-deploy-demo

live: http://ember-deploy-demo.ghedamat.com/

not sure if you think it would be a good idea to link it from the docs here or in the ember-deploy-redis package.

also, any feedback on the way I implemented it it's much appreciated :)

thanks!

**Comment by lukemelia** [comment]
@ghedamat Cool, looks great at first glance. I will review. I think @samselikoff might want to link to this from the ember-cli-deploy documentation site he is working on.

Related note: we're hoping to have as part of our test suite a smoke test that does an actual deploy. Any interest in helping out with that?

**Comment by ghedamat** [comment]
@lukemelia sounds good! as I said, feel free to open issues/pr if you see anything that should be tweaked in the demo.

Re: smoke test, I'm definitely very interested.
I haven't looked at the test suite and I'm not sure what we could do to make it work properly but I'd love to help! In roughly 10 days my schedule should free up enough, shall I ping you on irc/slack then?

**Comment by lukemelia** [comment]
@ghedamat yes, sounds good!

**Comment by ryanere** [comment]
:heart_eyes: so helpful!

**Comment by lukemelia** [comment]
This has now been linked in the docs.
