### ISSUE TITLE
Build takes considerably longer under deploy command

### ISSUE THREAD

**Issue by leojh** [ember-cli/ember-cli-deploy#152]
The build step takes considerably longer when running under "ember deploy" than when running simply under "ember build"
For me there is only a few seconds for build to finish under "build" but about 30 seconds or so under "deploy"

I'm running:
Ember 1.12
cli 0.2.7
ember-cli-deploy 0.4.1
ember-deploy-s3 0.0.4
ember-deploy-s3-index 0.4.0

**Comment by lukemelia** [comment]
@leojh Can you compare `ember build --environment production` to the build portion of `ember deploy`? The minification process can be slow.

**Comment by leojh** [comment]
Yes! great observation, completely missed this fact. Can you tell I haven't gone to production yet? :)

**Comment by lukemelia** [comment]
@leojh :) good luck shipping you app!

**Comment by leojh** [comment]
@lukemelia, another question for you. the docs for ember-cli-deploy lead me to believe that only production level deployments should get minification out of the box since it's depending on ember build behind the scenes. 

This is what the docs say:
"ember-cli will only create a production like build for the production-environment by default. If you want to support multiple 'production-like' environments you need to configure minification for these environments manually. You can do someting like this:"

can you shed some light on this?

**Comment by lukemelia** [comment]
It means that if you want a "staging" build environment in ember-cli that is minified like production, you will need to follow those directions. ember-cli-deploy adds the idea of a deployment target, and each deployment target can specify it's buildEnv, so the above advice is usually not necessary. e.g. the "staging" deploy target would be configured to use the "production" buildEnv.

**Comment by leojh** [comment]
@lukemelia that is basically what I got from it. So what is confusing me now, and goes back to my original issue, is that it would seem to me that minification takes place even when the environment is not "production" by default. So, in my case, when I do "ember deploy (defaults to development)" it still seems to be going through minification based on our assumption that it is the reason why it's taking so much longer to build.

**Comment by achambers** [comment]
For most cases we think users will want a production build even though
their deploy environment is not production. An example of this is that if
you deploy to a staging environment before production, you want your
staging environment to be as close to production like as possible. It
doesn't make sense deploying a build that doesn't look like production to a
staging environment.

Therefore, the convention is to deploy a production built set of assets to
your environments. If you want to differ from this you need to se the
buildEnv config to override this.

**Comment by leojh** [comment]
I don't disagree with that, and based on my observation, that is, indeed the behavior. I just got thrown off by what the docs state, which led me to believe that "deploy" works similar to "build." Thank you both very much for the clarifications. I'm very appreciative.

**Comment by achambers** [comment]
No probs mate. Good luck with your deployments and please let us know if
you have any other issues or questions.
