### ISSUE TITLE
Documentation for v0.5.0

### ISSUE THREAD

**Issue by achambers** [ember-cli/ember-cli-deploy#165]
This issue is a place to keep reminders about the things that should be documented as a part of the v0.5.0 pipeline.

- [x] `pipeline: {}` in deploy.js.  Supported properties being: `activateOnDeploy`
- [x] the intention of the `configure` hook and how it can be used to set the config to dynamically resovel values at runtime from the context object.
- [x] plugin name must be of format `ember-cli-deploy-<something>`
* [x] upgrading documentation for users(based on current md file in the repo)
- [x] Upgrade guide for plugin authors
* [x] fingerprinting specific page (based on 0.4.x) as it's a somewhat difficult concept for newcomers (@ghedamat)
* [ ] general copy editing (@samselikoff volunteered :) )
- [x] Explain how hooks that return values of hooks will be merged into the `context` object
- [x] Defining plugin aliases
- [x] Document dotenv support
- [x] ~~Mention fingerprint options that can be specified in `deploy.js`~~ (I don't think this is possible any longer - @achambers)
* [x] examples section, starting with lighting strategy examples, based on old ones from 0.4.x docs (@ghedamat)

This is related to #49 however it is more for the documentation site.  But we should make sure the two things are complimentary

**Comment by duizendnegen** [comment]
I'm working on point 4; upgrade guide for plugin authors

**Comment by achambers** [comment]
Nice work @duizendnegen. I have added it to the list.

**Comment by duizendnegen** [comment]
See https://github.com/ember-cli/ember-cli-deploy/pull/189

**Comment by lukemelia** [comment]
Combine this with #264, or vice versa?

**Comment by ghedamat** [comment]
will close 264 and move everything here @lukemelia

**Comment by ghedamat** [comment]
do we still need the `pipeline` config option with the `activateOnDeploy` key?

if so where do we wanna document it?

**Comment by lukemelia** [comment]
@ghedamat do we want to keep this issue open?

**Comment by ghedamat** [comment]
I think we covered pretty much everything here
