### ISSUE TITLE
Sha version in the output index.html?

### ISSUE THREAD

**Issue by juggy** [ember-cli/ember-cli-deploy#177]
I'd like a quick way to figure out what version is really showing up on the server and maybe add it to any bug reports from my users.

Is there a way to export the sha of the deployed version to the index.html file?

**Comment by lukemelia** [comment]
This could be pretty trivially implemented as a plugin in the upcoming 0.5.0 version. In general, I'm not sure where responsibility for this should lie between ember-cli-app-version and ember-cli-deploy.

**Comment by juggy** [comment]
Nevermind. It seems it is already listed in the ember inspector info tab. So I must have access to it in some way. Thanks!
