### ISSUE TITLE
How to use ember-deploy with AWS Elasticache redis cluster

### ISSUE THREAD

**Issue by quantumlicht** [ember-cli/ember-cli-deploy#183]
I spun up an AWS elasticache redis cluster, but now my deploy won't work

error: Error: Redis connection to my-cluster.usw2.cache.amazonaws.com:6379 failed - connect ETIMEDOUT
  at RedisClient.on_error (C:\Users\Quantik\git\whatsyourimpact\impact-frontend\node_modules\ember-deploy-redis\node_modules\redis\index.js:196:24)
  at Socket.<anonymous> (C:\Users\Quantik\git\whatsyourimpact\impact-frontend\node_modules\ember-deploy-redis\node_modules\redis\index.js:106:14)
  at Socket.emit (events.js:95:17)
  at net.js:440:14
  at process._tickDomainCallback (node.js:463:13)

Here's an exerpt of my deploy.js file:

 production: {
    store: {
      host: 'my-cluster.usw2.cache.amazonaws.com',
      port: 6379,
      password: 'AWS_SECRET'
    }

I tried setting the password with my AWS, but it's seems like it's not correct. Anyone tried this before?

**Comment by lukemelia** [comment]
I don't have much experience with AWS elasticache, but what little experience I do have left me believing that elasticaches instances could only be read from / written to from from an EC2 instance.

**Comment by LevelbossMike** [comment]
Haven't tried this as well but I think a ssh tunneling option was added because of this to `ember-deploy-redis` -> https://github.com/LevelbossMike/ember-deploy-redis#deploying-to-external-machine-reachable-through-ssh

**Comment by lukemelia** [comment]
This is solved in 0.5 by using the ember-cli-deploy-ssh-tunnel plugin https://github.com/ember-cli-deploy/ember-cli-deploy-ssh-tunnel
