### ISSUE TITLE
upload gets passed a buffer, not the html

### ISSUE THREAD

**Issue by duizendnegen** [ember-cli/ember-cli-deploy#19]
IndexAdapter.upload gets a buffer and not the Index HTML: http://nodejs.org/api/fs.html#fs_fs_readfile_filename_options_callback
This doesn't have to be a problem, but either the functionality should be updated, or the README.

**Comment by LevelbossMike** [comment]
thx i will look into this

**Comment by lukemelia** [comment]
This no longer is relevant in 0.5.0.
