### ISSUE TITLE
vendor assets encoding

### ISSUE THREAD

**Issue by MarkMT** [ember-cli/ember-cli-deploy#191]
I'm trying to do a development deploy of a test ember app, with the index file in redis on localhost accessed via a rails app and the assets uploaded to Rackspace Cloud Files using ember-deploy-cloudfiles. I'm having problems getting the browser to load the vendor assets properly.

In particular I'm finding that when I try to load the app, vendor.js and vendor.css are loaded with some kind of binary encoding that prevents them being interpreted by the browser (I get 'Uncaught SyntaxError: Unexpected token ILLEGAL' from vendor.js).

I've checked the files on the Rackspace server and they seem to be fine there - I can download them manually and read them as ascii.

I'm using gzip:false, but before I added this setting, I was also having the same problem with my 'test_app.*' assets. With the gzip:false setting the browser loads those assets properly.

Here's my deploy.js:

    module.exports = {
      development: {
        buildEnv: 'production',
        store: {
          type: 'redis', 
          host: 'localhost',
          port: 6379
        },
        assets: {
         type: 'cloudfiles',
         gzip: false,
         region: 'ORD',
         username: '......',
         apiKey: '......',
         container: 'static_assets'
        }
      }
    };

Any help greatly appreciated!

Mark

**Comment by MarkMT** [comment]
I have tried this with S3 as well, and found what appears to be the same problem with vendor.js, at least when loading the app using Chrome. Firefox seems to load the file ok. Here are the relevant links using both cloud platforms...

http://e3fd3b5bc2d2f3e9ccde-bd9acdc799c0f2664c47f2b1e3d01743.r87.cf2.rackcdn.com/assets/vendor-58ca80a4187f21cbd0b46d2353a5d5d3.js

https://s3.amazonaws.com/static-assets.mmt/assets/vendor-58ca80a4187f21cbd0b46d2353a5d5d3.js

**Comment by LevelbossMike** [comment]
This is odd. Do you have the same problem when uploading assets to s3 via ember-deploy-s3 without `gzip: false`?

**Comment by MarkMT** [comment]
Thanks Mike. That seems to have fixed it for s3. I can now see the app on localhost with assets served from s3. Any idea why `gzip: false` would not work?

I went back to Rackspace but still have the same problem there, so I'll follow up with them and at https://github.com/jschniper/ember-deploy-cloudfiles

**Comment by lukemelia** [comment]
Closing in favor of issue on plugin repo.

**Comment by devinrhode2** [comment]
I'm also seeing this error. adding `assets: { gzip:false }` doesn't do anything. I'm uploading to goddady via ftp, (with the ember cli ftp plugin) and these plugins:
```json
{
  "name": "ember-homepage",
  "version": "0.0.0",
  "description": "Small description for ember-homepage goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.2",
    "broccoli-clean-css": "1.1.0",
    "ember-ajax": "^2.0.1",
    "ember-browserify": "1.1.12",
    "ember-cli": "2.7.0",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-autoprefixer": "0.6.0",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-deploy": "1.0.0-beta.1",
    "ember-cli-deploy-build": "0.1.1",
    "ember-cli-deploy-ftp": "^1.0.0",
    "ember-cli-foundation-6-sass": "0.0.13",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-jshint": "^1.0.0",
    "ember-cli-qunit": "^2.0.0",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sass": "5.5.1",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.7.0",
    "ember-export-application-global": "^1.0.5",
    "ember-hammertime": "1.0.3",
    "ember-load-initializers": "^0.5.1",
    "ember-normalize": "1.0.0",
    "ember-redux": "1.5.3",
    "ember-resolver": "^2.0.3",
    "ember-suave": "4.0.0",
    "ember-truth-helpers": "1.2.0",
    "liquid-fire": "0.25.0",
    "loader.js": "^4.0.1",
    "normalize.css": "4.1.1",
    "redux": "3.6.0",
    "redux-thunk": "2.1.0"
  }
}
```
This issue doesn't occur when using filezilla. I'm not using the ember-deploy-cloudfiles
