### ISSUE TITLE
deploy sourcemaps to popular exception reporting services

### ISSUE THREAD

**Issue by jabbermarky** [ember-cli/ember-cli-deploy#201]
I use ember-cli-deploy for assets and index files currently. Now I am trying to integrate an exception reporting tool (evaluating rollbar and sentry). These tools support sourcemaps, but you need to upload the source map and/or minified source to a specific API endpoint. 

Does it make sense to extend ember-cli-deploy for this particular use case, or is this outside the scope?

**Comment by achambers** [comment]
@jabbermarky Yep, this will be a piece of cake for v0.5.0. You could easily pop a plugin into the deploy pipeline to do just that. A bit more difficult with the current version however. Are you in a position to wait until 0.5.0 drops?

**Comment by jabbermarky** [comment]
what is the timeframe for 0.5.0?

Mark
On Aug 13, 2015, at 11:50 AM, Aaron Chambers <notifications@github.com> wrote:

@jabbermarky <https://github.com/jabbermarky> Yep, this will be a piece of cake for v0.5.0. You could easily pop a plugin into the deploy pipeline to do just that. A bit more difficult with the current version however. Are you in a position to wait until 0.5.0 drops?

**Comment by achambers** [comment]
0.5.0-beta.1 was released a couple of days ago. We're working to get 0.5.0
out. So, as soon as we can.

**Comment by lukemelia** [comment]
Check out https://github.com/dschmidt/ember-cli-deploy-sentry. Creating a similar for rollbar shouldn't be doable if you decide to use them.

**Comment by duizendnegen** [comment]
:+1: if you need help with dev'ing rollbar, just drop by on Slack - I was involved in getting sentry to work & I'd be happy to help.

**Comment by LevelbossMike** [comment]
There's also https://github.com/simplabs/ember-cli-deploy-notifications that can be used to notify services of a deploy (i.e. activating a revision). It should be easy to adapt it to also upload files when running a hook.

**Comment by achambers** [comment]
@LevelbossMike / @duizendnegen : Are ember-cli-deploy-sentry and ember-cli-deploy-notifications essentially doing the same thing?

**Comment by duizendnegen** [comment]
Not really, `ember-cli-deploy-notifications` notifies configured services of deployment (passing a POST to a configured address); `ember-cli-deploy-sentry` is a full integration with Sentry in that it will create a new revision (analogous to POSTing to a configured address) plus upload sourcemaps.
@LevelbossMike mentioned that uploading files when running a hook is in the domain of possibilities - it'd be cool if we could generalize to cover all those scenarios, but I'm a tad skeptical.

**Comment by LevelbossMike** [comment]
It's kind of hard to draw the line were stuff like this could be generalized in a sane way. Sometimes services would need super special stuff like uploading specific files or just posting to a webhook. I don't think it would be hard to add the functionality to upload files to ember-cli-deploy-notifications but managing a lot of services in the plugin sure would be a pain and then all you are left with is a plugin that implements a hook that can be overriden by users.

If you don't need to do a lot (just POST to a webhook) ember-cli-deploy-notifications would be the way to go I guess. Uploading specific files (when each service differs by what it expects users to upload) would most likely belong in their separate plugin (like ember-cli-deploy-sentry)

**Comment by achambers** [comment]
Cool. Makes sense. Thanks
