### ISSUE TITLE
SVG assets

### ISSUE THREAD

**Issue by lcpriest** [ember-cli/ember-cli-deploy#217]
I am having issues with SVGs in production - all of the assets we use are in public/, should SVGs be in the images folder? I'm currently unable to see any.

**Comment by lukemelia** [comment]
You may need to add .svg to the filePattern used to determine which files to upload. What version of ember-cli-deploy are you using?

**Comment by lcpriest** [comment]
Version 0.4.3, is filePattern a configuration key? I can't see any mention of it in this repo.
P.S. amazing response time.

**Comment by lcpriest** [comment]
Ah, think I found it.
http://www.ember-cli.com/asset-compilation/#fingerprinting-and-cdn-urls

**Comment by lukemelia** [comment]
filePattern is a config option in 0.5.0 (beta). I don't see an equivalent in 0.4.3 looking at the code here: https://github.com/LevelbossMike/ember-deploy-s3/blob/master/lib/s3.js

**Comment by lcpriest** [comment]
Ah cool! What will that provide that the ember-cli-build.js does not?
That fixed it for me. 
```
    fingerprint: {
      prepend: 'https://s3.amazonaws.com/' + prepend,
      extensions: ['js', 'css', 'png', 'jpg', 'gif', 'map', 'svg']
    },
```

**Comment by lukemelia** [comment]
Glad you got it working! For a high-level overview of 0.5.0, check out https://github.com/ember-cli/ember-cli-deploy/blob/0.5.0-dev/rfc/plugins.md

**Comment by lcpriest** [comment]
Thanks, by the way - this was super helpful.
