### ISSUE TITLE
Dealing with dynamic asset urls

### ISSUE THREAD

**Issue by wehlutyk** [ember-cli/ember-cli-deploy#219]
First off, thanks for the fantastic addon :)

Maybe this doesn't pertain to ember-cli-deploy directly, but I can't find a clean way to deal with assets for which you compute the url at runtime: in my case I'm showing a png who's url is computed as `'assets/images/' + name + '.png'`. This url has to be converted to the CND'ed+fingerprinted version to work with ember-cli-deploy. Ways to do this:
* In  rickharrison/broccoli-asset-rev#24, @mksplg uses `assetMap.json` to compute at runtime, but with ember-cli-deploy this `assetMap.json` is also CDN'ed+fingerprinted! So no easy access to it
* [ember-cli-inject-asset-map](https://github.com/jcaffey/ember-cli-inject-asset-map) injects that same `assetMap.json` into a controller after the build has finished, but that seems terribly hackery (see [index.js](https://github.com/jcaffey/ember-cli-inject-asset-map/blob/master/index.js))

Would there be a way to hook into broccoli-asset-rev to make the assetMap available at compile-time?

**Comment by wehlutyk** [comment]
(In fact `assetMap.json` isn't fingerprinted by default, but that doesn't change anything to the problem.)

**Comment by lukemelia** [comment]
@wehlutyk I haven't done this with an ember-cli-deploy app, but it seems that you would need to have the contents of assetMap.json available to your Ember app one way or the other. I tend to agree about the approach used by ember-cli-inject-asset-map, but I'm not sure off the top of my head what the most elegant way would be. How do you (and others reading this) think ember-cli-deploy could best help with this?

**Comment by wehlutyk** [comment]
Well, it's either a post-build hack à la ember-cli-inject-asset-map, or there could be a way for broccoli-asset-rev to spit out a partial asset map early on. This would include the assets in `/public` only, and possibly the `vendor.{js,css}` ones, but the `app.{js,css}` need access to that map to be compiled, so they can't already be in it.

Then ember-cli could include that compile-time asset map in the build, and it could be imported as a js module in the app (like [ember-cli-json-to-js](https://github.com/ProlificLab/ember-cli-json-to-js)).

To be honest I know nothing about the internals of the build process, and most of all the order in which things happen, so I don't know if this is possible at all or if it's wild dreaming. @rickharrison would you maybe have thoughts about this?

**Comment by rickharrison** [comment]
There have been so many requests around dealing with the `assetMap.json` file. My general thoughts about this are that broccoli-asset-rev should only be responsible for one thing: fingerprinting the assets and generating the map. Any use of that map in a specific way should be done by the user in their own plugin after asset-rev has run. Unfortunately, it is just impossible to accommodate every single use case here.

I'm not familiar with ember-cli-deploy, but I would use the options here to not fingerprint the assetMap and then modify your deploy process to put the assetMap wherever it needs to be in order to read from it.

**Comment by wehlutyk** [comment]
That sounds right, thanks! So that rules out importing the assetMap as a module in the JS app itself. The options are:
* Non-fingerprinted `assetMap.json` in S3 (or equivalent long-life cache), which means devs must configure cache headers specifically for assetMap (otherwise when it changes, visitors get their cached assetMap is outdated)
* Non-fingerprinted `assetMap.json` on the server hosting `index.html`, which means changes to the redis setup (or equivalent)
* A better solution (in my opinion): trying to integrate the `assetMap.json` in the `index.html` itself (the same `config/environment.js` is integrated). If this can be done with a new addon that inserts itself in the build pipeline (after broccoli-asset-rev has produced the asset map), then it requires no changes to existing addons.

**Comment by rickharrison** [comment]
I haven't been in the ember world for a while, but I would try to make it available as part of the js build as a module.

So in code you can do:

```
import assetMap from './modules/assetMap';

assetMap[keyName]
```

**Comment by wehlutyk** [comment]
That's only possible if broccoli-asset-rev builds `assetMap.js` early enough in the build process, so that it can then be compiled in with the main app `.js` file. That's what I meant in my [previous comment](https://github.com/ember-cli/ember-cli-deploy/issues/219#issuecomment-142926241).

I don't know the inner workings of the build process, but as things stand now I can see it's not possible: the `assetMap.js` includes an entry for the main app `.js` file, and since the fingerprint for `app.js` is a hash of the final `app.js` file, I understand `assetMap.js` is built *after* the main app `.js` file is compiled (transpiled+concatenated+minified). So the final `assetMap.js` can't possibly be used in the main app by that mechanism, because it doesn't exist at compile-time yet.

I see two ways out of this:

* either there is a way to get access *at compile-time* to a partial `assetMap.js` (which doesn't include the `app.js` file, making it possible to build that partial asset map before `app.js` is compiled) -- that's what I was thinking in my above comment:
> there could be a way for broccoli-asset-rev to spit out a partial asset map early on. This would include the assets in /public only, and possibly the vendor.{js,css} ones, but the app.{js,css} need access to that map to be compiled, so they can't already be in it.

* or, there is a way to instruct the build pipeline that an `import assetMap from xxx/assetMap;` is valid even though the `assetMap.js` isn't available at compile-time, but will be included in the final `index.html` the same way `config/environment.js` is included.

(I might give a try at the second option if I get some time in a few weeks, it looks to me like the cleanest way to do it.)

**Comment by lukemelia** [comment]
I see no reason that the second option wouldn't be feasible @wehlutyk.

**Comment by lukemelia** [comment]
Closing as out of ember-cli-deploy's scope for further action at the moment.
