### ISSUE TITLE
Not able to use a single deploy adapter

### ISSUE THREAD

**Issue by ianwalter** [ember-cli/ember-cli-deploy#223]
I'm trying to use ember-cli-deploy to just upload my assets to s3 (I take care of the index.html separately).  If I don't specify a `store` attribute in my environment configuration and run `ember deploy` I get the following error:
```
Cannot set property 'manifestSize' of undefined
```
If I instead run `ember deploy:assets` I get:
```
ENOENT, no such file or directory 'tmp/deploy-dist//'
```
Is there a way I can accomplish this? Right now I'm just running `ember build` and then copying `dist/` to `tmp/deploy-dist` and then running `ember deploy:assets` but it seems strange that you're almost forced to use both deployment strategies.

**Comment by devinus** [comment]
I'm interested in this as well. Until https://github.com/ember-cli/ember-cli-deploy/issues/105 is resolved I only want to use `ember-cli-deploy` for assets.

**Comment by achambers** [comment]
@ianwalter / @devinus I'd suggest looking at ember-cli-deploy@0.5.0-beta.2 (0.5.0 proper soon to be released). This allows you to do exactly as you wish.

**Comment by kielni** [comment]
I'm getting this error with `ember deploy assets` and 

"ember-cli-deploy": "^0.5.0-beta.3"
"ember-deploy-s3": "0.0.5"

````
object is not a function
TypeError: object is not a function
    at Class.module.exports.Task.extend._pipelineConfig
````

**Comment by achambers** [comment]
@kielni You seem to be using ember-cli-deploy 0.5.0 with an adapter that is only compatible with 0.4.x. Also, ember deploy assets does not exist in 0.5.0 either. 

Please see the 0.5.0 specific docs @ ember-cli-deploy.com

**Comment by ianwalter** [comment]
I'm going to close this since you can do it in 0.5.0 and I no longer have the requirement.
