### ISSUE TITLE
Override `production` as the default deploy target.

### ISSUE THREAD

**Issue by kiwiupover** [ember-cli/ember-cli-deploy#226]
Our use case: A developer needs to specify a target when deploying to the production.

So `ember deploy production` makes sense when a developer is trying to push to development.
However is `ember deploy` defaults to push to production. 

We need away to override the behaviour. 

Where production is set as the default.
https://github.com/ember-cli/ember-cli-deploy/blob/v0.5.0-beta.2/lib/tasks/pipeline.js#L27

Proposed location for the override.

```js
module.exports = function(deployTarget) {
  var ENV = {
    defaultDeployTarget: 'staging',  //override here
    build: {
      outputPath: 'tmp/dist-assets'
    },
    'revision-data': {
      filePattern: 'do-not-compile.html'
    },
  ......
```

**Comment by lukemelia** [comment]
It's kind of awkward since this is inside a function that is called with a `deployTarget` argument. Might be better to do this inside of `ember-cli-build.js`

**Comment by kiwiupover** [comment]
@lukemelia you are right that is awkward. 

This would work soon?
```
module.exports = function(deployTarget='staging') {
  var ENV = {
    build: {
      outputPath: 'tmp/dist-assets'
    },
  ......
```
But we are in node land at this point and no babel.

**Comment by duizendnegen** [comment]
I planned to tackle this one of these days - feel free to bug me if I don't deliver

**Comment by kiwiupover** [comment]
I think Pepijn you will need look at ember-cli-deploy-build too.

**Comment by duizendnegen** [comment]
I think `ember-cli-deploy-build` is not in scope for this; it seems to me that the goal is not to build with a different environment but to deploy to a different environment instead.

Looking at `tasks/pipeline.js`, one way to achieve this would be to not set the environment in `init` but in `setup` instead - after `readDeployConfig`. Basically moving line 27-39 inside a different function. @lukemelia what do you think? Seeing that `pipeline.run` is the first thing executed & `setup` is the first command here, we should be able to get away with it.

**Comment by achambers** [comment]
Maybe this another example of a config property that exists under the top level `ENV.pipeline` property in deploy.js. An example of this is the `activateOnDeploy` option that is used in `lib/tasks/deploy`.

**Comment by achambers** [comment]
Now I'm looking at code on my computer as opposed to my phone I can clarify my thoughts. So...

`deployTarget` is optionally passed in to the command line and is first consumed [here](https://github.com/ember-cli/ember-cli-deploy/blob/master/lib/commands/deploy.js#L17) which is passed in to `tasks/deploy.js`.

`deployTarget` is then directly passed into `tasks/pipeline.js` and on initialisation of that class, if `deployTarget` is empty is it hardcoded to `production`.

I we go back to `tasks/deploy.js` you can see that [this function](https://github.com/ember-cli/ember-cli-deploy/blob/master/lib/tasks/deploy.js#L49) is used to get the `ENV.pipeline` config. This property could also be used to set the `defaultDeployTarget` property.

There is a slightly strange thing here in that that function passes in the current deploy target into the config function which, in our current case, would be null. So there is the chance that the user could try and use the deployTarget in the config file to determine some value for properties in the `ENV.pipeline` property. This doesn't make sense but it could happen.

Anyway, my current thinking is that maybe this is a good place to allow for the customised default deploy target.

Curious to see what @lukemelia's thoughts are.

**Comment by lukemelia** [comment]
Our resolution at today's face-to-face was to make `ember deploy` have no default deployTarget and raise an error if none is specified, unless you configure a defaultDeployTarget in ember-cli-build.js.

**Comment by lukemelia** [comment]
@kiwiupover if you want to help implement this, we'd be happy to provide guidance

**Comment by kiwiupover** [comment]
@lukemelia I think that is a great plan. So would the `ember-cli-deploy-build` have a blueprint that would update `ember-cli-build.js` to set `defaultDeployTarget: 'production'`  I think production is at least the  80% use case it just needs to be over written. 

I will not be able to get to this until next week. Is that timing ok?

**Comment by lukemelia** [comment]
That timing is fine @kiwiupover. A blueprint would be a cool way to approach it -- we hadn't thought of that. Personally, I would prefer that `ember deploy` with no deployTarget raise an error and make me specify where I am deploying.

**Comment by kiwiupover** [comment]
@lukemelia sounds good

**Comment by kiwiupover** [comment]
With #294 I don't think there is a need for a defaultDeployTarget.

I do have one question about the code. 

What how does this line work? `return fn(deployTarget)['pipeline'] || {};` from [here](https://github.com/ember-cli/ember-cli-deploy/blob/master/lib/tasks/deploy.js#L49-L61)

I know the deployTarget passed in is an object returned from the deploy.js file but what is the pipeline here `['pipeline']`

Cheers

**Comment by lukemelia** [comment]
@kiwiupover it's a top level property of the object returned from your `config/deploy.js` function
