### ISSUE TITLE
Deploy to CouchDB

### ISSUE THREAD

**Issue by broerse** [ember-cli/ember-cli-deploy#265]
I like to deploy to CouchDB design docs. I think I have to write this myself. I am new to ember-cli-deploy but it seems to me as the way to go. So my only question at the moment is how to deploy the ember production version to the various CouchDB's. I intent to adopt the [.couchapprc](http://guide.couchdb.org/draft/managing.html#configuring) file. Can I write something like this:

 - `ember deploy production default` 
 - `ember deploy production staging`
 - `ember deploy production drl`

Where `default`, `staging` and `drl` are CouchDB env's from the  [.couchapprc](http://guide.couchdb.org/draft/managing.html#configuring) file past on to the `ember-cli-deploy-couchdb` to create.

I hope someone can give me some pointers.

**Comment by lukemelia** [comment]
@broerse I think what you would want is to have a deploy target for each CouchDB environment you want to deploy to. So you would end up deploying with:

* `ember deploy default`
* `ember deploy staging`
* `ember deploy drl`

Each of the deploy targets would be configured to use ember's production build as well as to pass the couch environment on to the `ember-cli-deploy-couchdb` plugin that you will create.

**Comment by broerse** [comment]
@lukemelia Thanks. Have to think about this. If I want to run `ember deploy development staging` I have to configure 6 environments?

**Comment by broerse** [comment]
It is a little bit overhead in the `deploy.js` file but `ember deploy staging` is less typing ;-) Thanks will go with this.

**Comment by lukemelia** [comment]
@broerse sounds good. let us know if you run into any questions during your plugin development. We've started to collect some helpful docs in [the 0.5.x section of the docs site](http://ember-cli.github.io/ember-cli-deploy/docs/v0.5.x/)

**Comment by broerse** [comment]
@lukemelia My question is how to overwrite some ENV var from my plug-in See: https://github.com/ember-cli-deploy/ember-cli-deploy-build/issues/22

**Comment by broerse** [comment]
@lukemelia One other thing. In my tests it seems that ENV setting from deploy.overwrite default `defaultConfig`. This is expected. It also seems that if a setting is returned from a hook and returned in `defaultConfig` somewhere else it is also overwritten. Not expected. If you explicitly write `return context.distDir;` the setting should come from `context`. It seems an extra if is needed that does not overwrite a setting when it is in `context`

I hope it is clear what I like to say:
ENV.build.distDir => defaultConfig { distDir: }            // env overwites 
this.readConfig('distDir') + '/hash' => context.distDir    // changed distDir stored on context
context.distDir  => defaultConfig { distDir: }               // env overwites back to the original distDir from ENV.build
