### ISSUE TITLE
Add some sort of feedback when --verbose=false

### ISSUE THREAD

**Issue by achambers** [ember-cli/ember-cli-deploy#276]
Now that we have turned off the logging unless `--verbose` is set some people are feeling like they are missing some form of feedback that something is happening.

Might be worth thinking about adding some sort of simple spinner (maybe like `ember install` uses) when the `verbose` flag is false.

**Comment by ghedamat** [comment]
or maybe just a couple of simple

`starting deploy...`
`deploy done!`

messages?

**Comment by achambers** [comment]
Sure...Anything....It might be nice to use https://www.npmjs.com/package/pleasant-progress like ember-cli does to give a perception of something actively happening.

Dunno...It's just feedback I've been given based on the new "no output by default". While the general inspiration is "if there is no output then everything is good" maybe something small like this might be helpful.

**Comment by ghedamat** [comment]
understood

will see if I can do something on plane :D

**Comment by jrowlingson** [comment]
+1 - I spent more time than I should have last night trying to figure out why my plugin was not logging anything.

**Comment by ghedamat** [comment]
@jrowlingson you're talking about a plugin you're writing right?

for that we definitely need to add mention of the new `verbose` option
on the docs

http://ember-cli.github.io/ember-cli-deploy/docs/v0.5.x/writing-a-plugin/ 

I'll see if I can get to that as well while I fly to embercamp

**Comment by achambers** [comment]
Thanks @ghedamat.

**Comment by jrowlingson** [comment]
@ghedamat Yes, I have started working on the github plugin.

**Comment by ghedamat** [comment]
@jrowlingson glad to hear!

you probably figured it out already but you can do this
https://github.com/ember-cli-deploy/ember-cli-deploy-redis/blob/master/index.js#L69
to make the log always show

otherwise pass the `--verbose` option.

feel free to reach out on `#ember-cli-deploy` on the ember slack if you need help!

**Comment by lukemelia** [comment]
Closed by #280
