### ISSUE TITLE
Update plugin README's with ember-cli-deploy compatibility badges

### ISSUE THREAD

**Issue by achambers** [ember-cli/ember-cli-deploy#288]
Update the following repos:

### 0.5.0 Compatible (I think)

- [x] [duizendnegen/ember-cli-deploy-azure-blob](https://github.com/duizendnegen/ember-cli-deploy-azure-blob)
- [x] [duizendnegen/ember-cli-deploy-azure-tables](https://github.com/duizendnegen/ember-cli-deploy-azure-tables)
- [x] [jrowlingson/ember-cli-deploy-github](https://github.com/jrowlingson/ember-cli-deploy-github) (invalid name)
- [x] [dschmidt/ember-cli-deploy-cp](https://github.com/dschmidt/ember-cli-deploy-cp)
- [x] [minutebase/ember-cli-deploy-git-tag](https://github.com/minutebase/ember-cli-deploy-git-tag)
- [x] [minutebase/ember-cli-deploy-notify-firebase](https://github.com/minutebase/ember-cli-deploy-notify-firebase)
- [x] [ember-cli-deploy/ember-cli-deploy-build](https://github.com/ember-cli-deploy/ember-cli-deploy-build)
- [x] [ember-cli-deploy/ember-cli-deploy-gzip](https://github.com/ember-cli-deploy/ember-cli-deploy-gzip)
- [x] [ember-cli-deploy/ember-cli-deploy-redis](https://github.com/ember-cli-deploy/ember-cli-deploy-redis)
- [x] [ember-cli-deploy/ember-cli-deploy-manifest](https://github.com/ember-cli-deploy/ember-cli-deploy-manifest)
- [x] [ember-cli-deploy/ember-cli-deploy-revision-data](https://github.com/ember-cli-deploy/ember-cli-deploy-revision-data)
- [x] [ember-cli-deploy/ember-cli-deploy-s3](https://github.com/ember-cli-deploy/ember-cli-deploy-s3)
- [x] [ember-cli-deploy/ember-cli-deploy-json-config](https://github.com/ember-cli-deploy/ember-cli-deploy-json-config)
- [x] [ember-cli-deploy/ember-cli-deploy-display-revisions](https://github.com/ember-cli-deploy/ember-cli-deploy-display-revisions)
- [x] [ember-cli-deploy/ember-cli-deploy-ssh-tunnel](https://github.com/ember-cli-deploy/ember-cli-deploy-ssh-tunnel)
- [x] [simplabs/ember-cli-deploy-notifications](https://github.com/simplabs/ember-cli-deploy-notifications)
- [x] [ember-cli-deploy/ember-cli-deploy-s3-index](https://github.com/ember-cli-deploy/ember-cli-deploy-s3-index)
- [x] [ember-cli-deploy/ember-cli-deploy-slack](https://github.com/ember-cli-deploy/ember-cli-deploy-slack)
- [x] [pagefront/ember-cli-deploy-pagefront](https://github.com/pagefront/ember-cli-deploy-pagefront)
- [x] [dschmidt/ember-cli-deploy-sentry](https://github.com/dschmidt/ember-cli-deploy-sentry)
- [x] [arenoir/ember-cli-deploy-rsync](https://github.com/arenoir/ember-cli-deploy-rsync)
- [x] [pagefront/ember-pagefront](https://github.com/pagefront/ember-pagefront)
- [x] [duizendnegen/ember-cli-deploy-azure](https://github.com/duizendnegen/ember-cli-deploy-azure)
- [x] [ember-cli-deploy/ember-cli-deploy-lightning-pack](https://github.com/ember-cli-deploy/ember-cli-deploy-lightning-pack)

### 0.5.0 Incompatible
- [x] [eddflrs/ember-cli-deploy-ssh](https://github.com/eddflrs/ember-cli-deploy-ssh)
- [x] [Kerry350/ember-deploy-s3-index](https://github.com/Kerry350/ember-deploy-s3-index)
- [x] [he9qi/ember-deploy-alioss](https://github.com/he9qi/ember-deploy-alioss)
- [x] [langalex/ember-deploy-rest-api](https://github.com/langalex/ember-deploy-rest-api)
- [x] [jschniper/ember-deploy-tagging-env](https://github.com/jschniper/ember-deploy-tagging-env)
- [x] [kinesisptyltd/ember-deploy-rest](https://github.com/kinesisptyltd/ember-deploy-rest)
- [x] [arenoir/ember-cli-deploy-rsync](https://github.com/arenoir/ember-cli-deploy-rsync)
- [x] [leojh/ember-deploy-rest-index](https://github.com/leojh/ember-deploy-rest-index)
- [x] [rtablada/ember-deploy-s3-index](https://github.com/rtablada/ember-deploy-s3-index)
- [x] [LevelbossMike/ember-deploy-s3](https://github.com/LevelbossMike/ember-deploy-s3)
- [x] [treyhunner/ember-deploy-ssh-index](https://github.com/treyhunner/ember-deploy-ssh-index)
- [x] [jschniper/ember-deploy-cloudfiles](https://github.com/jschniper/ember-deploy-cloudfiles)
- [x] [eddflrs/ember-cli-deploy-ssh](https://github.com/eddflrs/ember-cli-deploy-ssh)
- [x] [damon-lanphear/ember-deploy-dynamodb](https://github.com/damon-lanphear/ember-deploy-dynamodb)
- [x] [aptible/dashboard.aptible.com](https://github.com/aptible/dashboard.aptible.com)
- [x] [LevelbossMike/ember-deploy-redis](https://github.com/LevelbossMike/ember-deploy-redis)
- [x] [Scalingo/ember-deploy-tagging-scalingo](https://github.com/Scalingo/ember-deploy-tagging-scalingo)
- [x] [jcaffey/ember-deploy-ssh-index](https://github.com/jcaffey/ember-deploy-ssh-index)
- [x] [alisdair/ember-deploy-tagging-git](alisdair/ember-deploy-tagging-githttps://github.com/alisdair/ember-deploy-tagging-git)
- [x] [jamesfid/ember-deploy-tagging-index-sha](https://github.com/jamesfid/ember-deploy-tagging-index-sha)
- [x] [plyfe/ember-deploy-package-tagging](https://github.com/plyfe/ember-deploy-package-tagging)
- [x] [dukex/ember-cli-deploy-github](https://github.com/dukex/ember-cli-deploy-github)
- [x] [waltznetworks/ember-deploy-couchbase](https://github.com/waltznetworks/ember-deploy-couchbase)
- [x] [automategreen/ember-deploy-dynamodb](https://github.com/automategreen/ember-deploy-dynamodb)
- [x] [cnerepo/ember-cli-deploy-redis-cne](https://github.com/cnerepo/ember-cli-deploy-redis-cne)

**Comment by kpfefferle** [comment]
[kpfefferle/ember-cli-deploy-cloudfront](https://github.com/kpfefferle/ember-cli-deploy-cloudfront) is also 0.5.0 compatible and I would welcome a PR to add a version badge (or instructions how to add one myself).

**Comment by ghedamat** [comment]
@kpfefferle please do, https://github.com/ember-cli-deploy/ember-cli-deploy-version-badges

I plan to do some more work there to give us better colored badges but that should not affect the format 

you can use

https://github.com/ember-cli-deploy/ember-cli-deploy-version-badges/blob/gh-pages/plugins/ember-cli-deploy-s3.md

as an example

thanks!

**Comment by ghedamat** [comment]
:boom: just opened a LOT of PRs
