### ISSUE TITLE
Sharing configuration objects not possible

### ISSUE THREAD

**Issue by duizendnegen** [ember-cli/ember-cli-deploy#299]
Noted in https://github.com/ember-cli-deploy/ember-cli-deploy-s3-index/issues/21 in sharing s3 with s3-index config, fix attempted in https://github.com/ember-cli-deploy/ember-cli-deploy-plugin/pull/3

However, we should do it in ember-cli-deploy proper and not in the base plugin - that's why I'm opening this issue here.

To be fixed by deep cloning the config after resolving it from the deploy.js function.

**Comment by lukemelia** [comment]
I think this can be closed. @duizendnegen reopen if I'm mistaken.
