### ISSUE TITLE
Get version + version of plugins installed

### ISSUE THREAD

**Issue by Tecktron** [ember-cli/ember-cli-deploy#302]
Maybe it's just not documented or documented well, but how do I tell what version of ember-cli-deploy is installed and how do I tell what version of a plugin is installed?

I tried:
- `ember version --verbose` offers nothing and I feel like this should list the deploy version
- `ember deploy:versions` is an invalid command, although listed in help but with no entry so maybe it's for something else, but maybe this should list the installed plugins and their versions?

**Comment by lukemelia** [comment]
@Tecktron Can you tell us more about what your use case is? Normally, I just look at my package.json file, though I can imagine a command being helpful.

**Comment by Tecktron** [comment]
Just trying to quickly check if the packages are installed via a script before installing them (or not). Easier to parse a few lines of bash output, but I understand if it's not on a priority list and more of a nice to have.

**Comment by lukemelia** [comment]
@Tecktron you might want to take a look at: https://github.com/rwjblue/ember-cli-version-checker

**Comment by Tecktron** [comment]
Will do. Thanks.

**Comment by ghedamat** [comment]
@lukemelia shall we close this?

maybe there's a command to be added here although I feel that a look at `package.json` is probalby enough for now

**Comment by lukemelia** [comment]
Not a priority right now.
