### ISSUE TITLE
Allow plugin packs to provide config?

### ISSUE THREAD

**Issue by lukemelia** [ember-cli/ember-cli-deploy#303]
In Slack, @mmun said "My primary use case is that I'd like to have an internal build pack for my company that is parameterized across projects only by env vars, and updates to the build should only require updating package.json in each project."

Let's use this issue to discuss how this might work and what the API would be like.

**Comment by achambers** [comment]
Not 100% clear on what this use case looks like. Any more information that could make it clearer for me?

By internal build pack you mean plugin pack I assume?

**Comment by mmun** [comment]
@achambers Yes, sorry -- deploy pack. Our deploy involves sendings messages to slack and github. Configuring these in each project (and keeping them maintained) can be a burden.

**Comment by mmun** [comment]
The TL;DR is: The more plugins that your plugin packs includes, the more configuration you need to keep maintained across all the projects.

**Comment by mmun** [comment]
As a concrete example, if you decide to customize the `username` field of `ember-cli-deploy-slack` to contain the name of the project, you need to go through each project and modify the config/deploy.js file accordingly.

**Comment by achambers** [comment]
Ahh. Got ya. So the plugin pack could define the default config/deploy.js and your projects would just supply env vars for things like `username` in your example. 

And then projects could provide their own deploy.js which could override or be merged with the plugin pack supplied one. 

Awesome stuff. I like where this is going. 

Thanks for pushing these ideas forward @mmun

**Comment by duizendnegen** [comment]
As a workaround (but possibly as a main flow), wouldn't you be able in your deploy.js to do something like

```javascript
var dotenv      = require('dotenv');

module.exports = function(environment) {
    var dotEnvFilename = '.env.deployUser';
    // load vars from dotEnv here, or provide defaults
}
```

... and maintaining a `.env.deployUser` file for every dev?

**Comment by mmun** [comment]
The issue is that you need to have code like this duplicated across all your projects.

```js
    slack: {
      webhookURL: process.env.SLACK_WEBHOOK,
      username: function(context) {
        var name = inflected.titleize(context.project.name());
        var target = inflected.titleize(deployTarget);

        return 'Ember - ' + name + ' ' + target;
      }
    }
```

**Comment by ghedamat** [comment]
:+1: for this, having multiple apps for the same client I'm definitely starting to feel the same pain.

**Comment by lukemelia** [comment]
We've demonstrated how to do this using normal node semantics here: https://github.com/yappbox/ember-cli-deploy-yapp-pack/blob/master/index.js

Do we need more than this? Perhaps we should document this approach?

**Comment by lukemelia** [comment]
I added a paragraph to the 0.6.x website docs about how to do this in #335

**Comment by ghedamat** [comment]
@lukemelia just tried this approach today and it worked great! Thanks!
