### ISSUE TITLE
how to get deployTarget in ember-cli-build.js

### ISSUE THREAD

**Issue by danielspaniel** [ember-cli/ember-cli-deploy#304]
I think the build pipeline takes the command:   ember deploy staging 

 and builds with environment: 'production'  with deployTarget: 'staging'

 the problem is during the build ( in ember-cli-build.js )  I need the real environment 'staging' to get the correct fingerprinting URL to cloudfront.  

 Any suggestions?  Is there a way to get the deployTarget variable from the ember-cli-build ?

**Comment by danielspaniel** [comment]
I noticed that you set the process.env.DEPLOY_TARGET 

```
  run: function(commandOptions, rawArgs) {

    commandOptions.deployTarget = rawArgs.shift();
    this.ui.verbose = commandOptions.verbose;
    process.env.DEPLOY_TARGET = commandOptions.deployTarget;  // <<  HERE

    var DeployTask = require('../tasks/deploy');
    var deploy = new DeployTask({
      project: this.project,
      ui: this.ui,
      deployTarget: commandOptions.deployTarget,
      deployConfigFile: commandOptions.deployConfigFile,
      commandOptions: commandOptions
    });

    return deploy.run();

  },
```

so I used that in the ember-cli-build.js to get the depoy_target ..
 
Hopefully others find that useful, or maybe there is a more slick way to do this?

**Comment by achambers** [comment]
That's a perfectly good solution :)

I'll close this seeing you've answered your own question. Reopen if you have any other questions.
