### ISSUE TITLE
Backslashes mess up deploying to S3 on Windows

### ISSUE THREAD

**Issue by AW-UC** [ember-cli/ember-cli-deploy#306]
I am running *Windows 7, 64 bit* and am deploying with **ember-cli-deploy 0.5.1** & **ember-cli 1.13.8** to **S3**. Builds in `deploy-dist` are fine, but on uploading assets the backslashes are not converted to slashes. Thus, in my bucket I have a file named like `assets\vendor-94d0c52583a18e95729ebf70f10f3ade.js` instead of `vendor-94d0c52583a18e95729ebf70f10f3ade.js` in the folder `assets`.

**Comment by lukemelia** [comment]
@AW-UC thanks for the report. Would you mind opening this issue on http://github.com/ember-cli-deploy/ember-cli-deploy-s3? That's where it will need to be fixed.

**Comment by AW-UC** [comment]
Sure. New issue here: https://github.com/ember-cli-deploy/ember-cli-deploy-s3/issues/33
