### ISSUE TITLE
Programatically fetch revisions in a deploy process.

### ISSUE THREAD

**Issue by tim-evans** [ember-cli/ember-cli-deploy#309]
For our build process, we would like to provide a diff between the last version deployed and the current version. Currently, we need to shell out to get the revisions and parse the text. It would be nice to be able to get access to the revisions / active revision from a deploy plugin.

**Comment by duizendnegen** [comment]
This is in theory relatively easy - the list command expects other plugins (azure-tables, Redis) to fetch revisions like you want, then display them.However, the listing revisions is not in the build pipeline - can you elaborate how your envisioned build process looks and at what time you need what information + what you use the build for (dev, prod, otherwise)?

**Comment by tim-evans** [comment]
We send a slack message showing the diff (repo information removed):

<img width="535" alt="screen shot 2015-11-24 at 4 13 21 pm" src="https://cloud.githubusercontent.com/assets/177701/11380847/9c198e6c-92c6-11e5-9280-0098cc47f329.png">

**Comment by duizendnegen** [comment]
I'm trying to see what's the best approach to this along with the maintainers, routes are
* support custom pipelines (ember deploy deploy-with-github)
* support existing non-standard hooks within a pipeline (ember deploy, with in deploy.js an option to pick 'n mix additional plugin hooks)
* support new hooks within a pipeline (like the previous, but not limited to 'fetchRevisions' and 'displayRevisions', rather 'fetchRevisions' and 'displayThisGithubThing')

**Comment by lukemelia** [comment]
I would like there to be a standard context addition for plugins that implement the activate hook: `revisionData.activatedRevisionKey`. The redis plugin already adds this and others do too. Perhaps there should be an additional standard context addition: `revisionData.previousRevisionKey`. It sounds like those two piece of information would be enough to generate the notification message that @tim-evans wants. Thoughts?

**Comment by duizendnegen** [comment]
:+1:

**Comment by LevelbossMike** [comment]
:+1:

Sounds good. Should be enough for people to be able to enrich the deploy context via in-repo addons (maybe in the didDeploy or didActivate hooks) then if they have very custom needs.

**Comment by tim-evans** [comment]
That would do the trick @lukemelia! (for the code, see https://github.com/movableink/ember-cli-deploy-ink-pack, specifically https://github.com/movableink/ember-cli-deploy-ink-pack/blob/master/lib/ember-cli-deploy-ink-plugin/index.js#L103)

**Comment by duizendnegen** [comment]
See https://github.com/ember-cli-deploy/ember-cli-deploy-redis/pull/47 (nice and tested), https://github.com/duizendnegen/ember-cli-deploy-azure-tables/pull/1 (ugly and hacked)
I've left ember-cli-deploy-s3-index for others to implement.

Feedback welcome - directly here as for this use case, or on the relevant PRs for potential oversights

**Comment by LevelbossMike** [comment]
:+1: I'll add this to ember-cli-deploy-s3-index in the next days as well

**Comment by duizendnegen** [comment]
Closing this, `redis` and `azure-tables` support this now. Feel free to re-open if not supported adequately, or raise an issue on the specific repos.
