### ISSUE TITLE
Lightning Strategy page is empty

### ISSUE THREAD

**Issue by pablobm** [ember-cli/ember-cli-deploy#330]
See:

http://ember-cli.com/ember-cli-deploy/docs/v0.5.x/the-lightning-strategy/

I understand there's a [pull request in the works], but it's confusing to readers.

[pull request in the works]: https://github.com/ember-cli/ember-cli-deploy/pull/261

**Comment by lukemelia** [comment]
Addressed for 0.6x docs in #335. Not live yet, but closing this issue to keep the 0.6.x milestone up-to-date.

**Comment by tannerthayer** [comment]
agreed with pablobm
