### ISSUE TITLE
Different robots.txt for production and staging 

### ISSUE THREAD

**Issue by broerse** [ember-cli/ember-cli-deploy#332]
Not really an issue but related to deploy-packs: 

http://discuss.emberjs.com/t/different-robots-txt-for-production-and-staging/

**Comment by ghedamat** [comment]
@broerse looks like you got it working in your plugin right? if so maybe this can be closed and might be material for a cookbook session once we have it on the docs website

**Comment by broerse** [comment]
@ghedamat Yes it works in my plugin. I had to use `postBuild` to do it. It made me aware the current ember-cli-deploy setup only supports runs the `build` hook and not `preBuild` and `postBuild` hook. Perhaps I need to improve that in my plugin. If you think we should support more from the [list](https://github.com/ember-cli/ember-cli/blob/master/ADDON_HOOKS.md) please let me know.
