### ISSUE TITLE
requiredConfig and nested config objects

### ISSUE THREAD

**Issue by MojoJojo** [ember-cli/ember-cli-deploy#333]
Hi,

I'm writing a plugin for ember-cli-deploy and have a situation where the config can accept nested configuration objects. For instance, in my deploy.js, the config could look like:

```
ENV['dukstra-sftp']: {
        sftpOptions: { 
        username: 'secret',
        .........
        .........
        },
       pluginFeatureA: true,
        .........
        .........       


}
```
It seems like in index.js for my plugin, I can only check for simple parameters and not complex ones:
```
requiredConfig: ['sftpOptions']  //This works
requiredConfig: ['sftpOptions', 'pluginFeatureA'] //Also works
requiredConfig:['sftpOptions.username'] //Does not work.

```
I can easily override the ensureConfigPropertySet method in the plugin, but was wondering if it should be  feature available to plugin developers or if I should re-structure my plugin? Give then current state of the project, is overriding the ensureConfigPropertySet the only option?

**Comment by lukemelia** [comment]
We have no religious opposition to nested config objects, but there should be a pretty compelling reason for it, IMO. Simple properties are easier to work with for both plugin devs and end-users.

**Comment by achambers** [comment]
Closing due to no "compelling reason" presented for discussion.

**Comment by knownasilya** [comment]
A compelling reason is to preserve config options from other tools, which the plugin wraps.
For example, I'm writing a gcloud-storage plugin and that takes a config like so:

```js
var gcloud = require('gcloud')({
  credentials: {
    'private_key': auth.key,
    'client_email': auth.email
  },
  projectId: auth.project
});
```

I want to preserve this for consistency.
