### ISSUE TITLE
auto-install ember-cli-deploy-build depedency?

### ISSUE THREAD

**Issue by blimmer** [ember-cli/ember-cli-deploy#346]
The move to an extremely modular pipeline was a great move. That said, should we hook into the "default blueprint" behavior of ember-cli and install (at least) ember-cli-deploy-build for first-time users? Seems like this could be a hard stopping point for a lot of newbies.

**Comment by lukemelia** [comment]
I'm of two minds. On the one hand, it would be nice since practically every user needs that one. On the other hand, you still have a pipeline that doesn't really do much, and you no longer get the helpful output explaining that you will need plugins and directing you to the website listing. I'd lean toward leaving it as is but open to other opinions.

**Comment by blimmer** [comment]
I can definitely see both sides of the argument. My only worry is that people get discouraged from using this awesome resource because they "can't even get it to build".

**Comment by ghedamat** [comment]
@lukemelia @blimmer maybe we should think about a post-install message?

something to trigger only after `ember install ember-cli-deploy` that links to docs?

**Comment by lukemelia** [comment]
@ghedamat I like the way you think: https://github.com/ember-cli/ember-cli-deploy/blob/master/blueprints/ember-cli-deploy/index.js#L12

**Comment by ghedamat** [comment]
lol :D 
didn't even remember doing that, sorry!

shall we extend that message specifically warning people about the build plugin? or do something else? or just close this issue?

**Comment by lukemelia** [comment]
I think we can close it. I appreciate Ben's concern about the new user
experience, and we should try to make it great, but we haven't seen any
evidence that this particular issue is a problem.

**Comment by blimmer** [comment]
Sounds good to me! Closing.
