### ISSUE TITLE
Fingerprinting SVG assets.

### ISSUE THREAD

**Issue by mswanson** [ember-cli/ember-cli-deploy#363]
I have ember deploy setup to deploy everything to an S3 bucket. I am having caching issues with the SVG assets in the `public/assets/images` directory. All the other assets get fingerprinted when deploying to S3 however svg files do not. I may be missing a configuration or something, but is there a way to get those fingerprinted? My deploy config looks like this:

```javascript
module.exports = function(deployTarget) {
  var ENV = {
    build: {
      environment: 'production'
    },
    pipeline: {
      activateOnDeploy: true
    },
    s3: {
      accessKeyId: process.env.AWS_KEY,
      secretAccessKey: process.env.AWS_SECRET,
      region: process.env.AWS_REGION,
    },
    's3-index': {
      allowOverwrite: true,
      accessKeyId: process.env.AWS_KEY,
      secretAccessKey: process.env.AWS_SECRET,
      region: process.env.AWS_REGION
    },
...
};
```

**Comment by lukemelia** [comment]
You'll want to add `svg` to the list of fingerprinted extensions in your [https://github.com/rickharrison/broccoli-asset-rev#usage](broccoli-asset-rev) configuration within ember-cli-build.js

**Comment by mswanson** [comment]
cool thanks @lukemelia

**Comment by lcpriest** [comment]
The link luke posted looks right, but is actually broken: 
https://github.com/rickharrison/broccoli-asset-rev#usage
