### ISSUE TITLE
Add a note into the documentation about fingerprint.prepend

### ISSUE THREAD

**Issue by varblob** [ember-cli/ember-cli-deploy#43]
I just read this article by @Kerry350 and it mentioned adding fingerprint.prepend to get the files prepended with the cdn url.  Whilst I know this isn't technically part of ember-cli-deploy it would be nice to put a note in the documentation.

**Comment by danshultz** [comment]
One item to note (@Kerry350 - I don't think I mentioned this yesterday), the `prepend` should be a value like `//<your-assets>.s3.amazonaws.com/` (include slashes).

As another reference, for a more complex scenario with different environment deploys, I'm doing something like the following...

```javascript
/* global require, module, process */

var EmberApp = require('ember-cli/lib/broccoli/ember-app');
var env = EmberApp.env();
var isProductionBuild = ['production', 'stage'].indexOf(env) > -1;

var config = require('./config/environment')(env);

var app = new EmberApp({
  vendorFiles: { 'handlebars.js': null },
  fingerprint: { prepend: config.assetPrefix },
  minifyCSS: { enabled: isProductionBuild },
  minifyJS: { enabled: isProductionBuild },
  tests: process.env.EMBER_CLI_TEST_COMMAND || !isProductionBuild,
  hinting: process.env.EMBER_CLI_TEST_COMMAND || !isProductionBuild,
});

```

**Comment by Kerry350** [comment]
@danshultz Yeah, checking the article it's not explicit about the forward slash being needed, I'll add it in now (you miss the silliest things writing stuff up). I'll make it schemeless too.

Thanks for your environment snippet. I'm enjoying seeing how everyone is handling this.

@varblob Hope the article was useful in some way :)

**Comment by varblob** [comment]
@Kerry350 I was stuck on the link rewriting issue until I found out about the prepend through your article.  I realize I forgot to link to it in my original comment.  http://kerrygallagher.co.uk/making-ember-deploy-adapters/ for posterity.
