### ISSUE TITLE
Confirm Travis build is still working after migration

### ISSUE THREAD

**Issue by achambers** [ember-cli/ember-cli-deploy#45]
- [x] Confirm build works
- [x] Update build badge in README

**Comment by LevelbossMike** [comment]
Travis should be easy because it was already running on travis.

**Comment by achambers** [comment]
Ah, so it was.  I missed that.  Didn't realise the travis config was a hidden file.  I was looking for `travis.yml`

**Comment by achambers** [comment]
I guess, let's use this issue to make sure it's still working ;)

**Comment by achambers** [comment]
@LevelbossMike I haven't used Travis before really.  Any idea why this can't find the .travis.yml? https://travis-ci.org/ember-cli/ember-cli-deploy

**Comment by achambers** [comment]
Closed in #44
