### ISSUE TITLE
Move deployment config to per-environment .js files

### ISSUE THREAD

**Issue by lukemelia** [ember-cli/ember-cli-deploy#46]

**Comment by danshultz** [comment]
@lukemelia - I was coming here to start a PR regarding this. I was thinking though that the deployment config works well as a single file but was thinking it would make sense to specify the `deployment config` via a param `ember deploy --config production-deploy.js`

This opens up the option for the deploy config to reference env variables also which is helpful for aws credentials and other sensitive credentials.

**Comment by LevelbossMike** [comment]
I agree that we should move to .js-files to be able to reference ENV-variables but do we really need multiple deploy-config files? Ember-CLI itself is using one environment-config file. This seems like a hurdle for new users to me instead just using `deploy.js`. Users have to pass `--environment <something>` anyway to the `deploy`-command to build correctly.

**Comment by achambers** [comment]
I just felt like it's a nicer separation of responsibilities. The user passes in --environment=staging which, by convention used staging.js. 

They are much of a muchness really. I'm just a fan of logically separated things instead of a god file, which could potentially become quite large. 

I guess it's just a matter of style. I'm easy either way.

**Comment by lukemelia** [comment]
I'm convinced for now by the argument in favor of the single .js file (that we should match ember-cli's convention). We can revisit if it causes an issue.

**Comment by achambers** [comment]
We still need to actually do that though right @lukemelia ?  Currently it's a deploy.json file in the root of the project.  So work will still need to be done to make it work with the single .js file in the config directory.

**Comment by lukemelia** [comment]
@achambers it currently works with .js. I opened #51 to track the deprecation.

**Comment by danshultz** [comment]
I also think it's more consistent and keeps things in a single config file.

@achambers supporting a default single file, e.g. `config/deploy.js` gives the user the flexibility to break things into separate files if that is their preference. One can simply require the separate files into their `config/deploy.js` if things get to a point where it's necessary to slice and dice for a more complex setup.

**Comment by lukemelia** [comment]
@danshultz good point

**Comment by achambers** [comment]
Yep, sounds good @danshultz
