### ISSUE TITLE
Deployment pipeline for 0.5.0

### ISSUE THREAD

**Issue by ryanto** [ember-cli/ember-cli-deploy#47]
# Deployment pipeline

We can look at deploys are a series of steps that change the state of our production application. Our plan is to provide hooks that represent the common steps that you would find in the deployment lifecycle of an Ember application. Deploy adapters will be able to hook onto one or more of the pipeline steps to add functionality to the deploy.

### Proposed steps

1. willDeploy
1. build
1. update
1. activate
1. didDeploy

Questions / comments:
* Is it worth providing an API for adding a step?

### Hooks

Adapters will register themselves with one or more of the hooks to provide functionality. Registration is done by having a function named `deployHookName` on the adapter object.

```javascript
S3Adapter = {
  deployAssets: function(deploy) {
    var results = this.uploadAssets();
    ...
  }
}
```
*Edited to match luke's comment below.*

Questions / comments

* Does order matter? If I register two adapters to ``build`` hook is there a situation where I need to control which gets run first?

### Default adapters

By default ember-cli-deploy will ship with a `BuildDistAdapter` that hooks into the `build` step. This runs `ember build`. It's a good example of a simple adapter + hook, 99% of people will use it, and it easy to override if you need different build-to-dist functionality.

Questions / comments:

* Does this mean we need to provide an API for removing adapters from hooks?

### Shared state and deploy metadata

Adapters may want to share data with other adapters that may run later in the lifecycle. For example a post-deploy adapter may want to summarize all the work done by your build, asset, and index adapters.

There will be an API to read the return values from other adapters. Consider it unstable and not encouraged, but it will be there to see if this is something useful to provide. If we notice of pattern of adapters sharing information we can hopefully provide a shiny API.

**Comment by lukemelia** [comment]
Perhaps an adapter should simply implement the methods that it wants to use (a la ember-cli's addon API).

```javascript
S3Adapter = {
  deployAssets: function(deploy) {
    var results = this.uploadAssets();
    ...
  }
}
```

Also, adapters should likely be returning promises from the hooks since most operations will be async.

**Comment by ryanto** [comment]
Looks good.

:+1: on adapters returning promises. I'll open a new ticket for adapter API.

**Comment by achambers** [comment]
:+1:  Looks good.

**Comment by ryanto** [comment]
@achambers Yup

**Comment by achambers** [comment]
Part of me feels like adapter should really be independent of each other.  If adapters start to depend on other adapters, this feels quite brittle.  I'm sure this will become clearer as we move on, but I suspect we might find encouraging adapters to be self sufficient might be the way to go.  I sort of see these to be similar to Tasks in ember-cli.

**Comment by samselikoff** [comment]
I'm thinking we shouldn't use the term adapter. It suggests a single unit that gets swapped in and out with other adapters. And this is not appropriate - these units need to be mixed, composed, and overridden with more granularity than that.

What about tasks?

`ember deploy` triggers the deploy process, which runs through the following hooks:

- willDeploy
- deploy
  - willBuild
  - build
  - didBuild
  - willUpdate
  - update
    - willUpdateIndex
    - updateIndex
    - didUpdateIndex
    - willUpdateAssets
    - updateAssets
    - didUpdateAssets
  - didUpdate
  - willActivate
  - activate
  - didActivate
- didDeploy

For each hook, all registered tasks are executed. Users can register tasks within their application like this:

```js
// config/deploy-tasks.js
export default {
  build: function() {
    `ember build`; // whatever api this will be
  },

  update: function() {
    `rsync /to/some/path`;
  },

  didDeploy: function() {
    console.log('You did it!');
  }
}
```

`ember-cli-deploy` would take this file, and add each of these tasks to its registry under the appropriate hook and a namespace. Since this config file is part of the host app, it would be added under the host app's prefix:

```
console.log(deploy.registeredTasks);
/*
[
 {name: 'my-app:build', task: function() {`ember build...`},
 {name: 'my-app:update', task: function() {...} },
 {name: 'my-app:didDeploy', task: function() {...} }
]
*/

In this case, these are the only three tasks registered, so `ember deploy` would just execute them in order.

Now, say the user wants to upload everything to S3. He deletes the `update` task that he wrote, and finds the ember-cli-deploy-s3-plugin, which adds several tasks to his deploy pipeline. After installing it he can view everything that's been registered via some api:

```
console.log(deploy.registeredTasks);
/*
[
 {name: 'my-app:build', task: function() {`ember build...`},
 {name: 'my-app:didDeploy', task: function() {...} },
 {name: 'ember-cli-deploy-s3-plugin:willUpdate', task: function() {...} },
 {name: 'ember-cli-deploy-s3-plugin:update', task: function() {...} },
 {name: 'ember-cli-deploy-s3-plugin:didDeploy', task: function() {...} }
]
*/
```

This particular plugin has added three tasks, to the `willUpdate`, `update` and `didDeploy` hooks. There are now two tasks registered to `didDeploy`. By default they'll get run in no particular order, but the user can also specify which ones get run before or after, via some api. The user can also disable tasks that were imported via the plugin, if for example he wants to silence whatever is run in `ember-cli-deploy-s3-plugin:didDeploy`, via some api.

----

With something like this, the deploy pipeline stays customizable by the host app. By default ember-cli-deploy will have things like `ember build` for the build hook, maybe some notifications for the `willDeploy` and `didDeploy` hooks, but they'll all be namespaced ('ember-cli-deploy:build') and thus overridable/customizable by the host app.

This also makes it easy for users to just install an `ember-cli-deploy-slack-notifier` that just registers a task in the `didDeploy` or `didActivate` hooks. It wouldn't interfere with any other tasks that have been registered, it would be under its own namespace, it could be customizable by the host app, etc.

Thoughts?

**Comment by samselikoff** [comment]
task is just concept/idea, not referring to Ember CLI's tasks

**Comment by ryanto** [comment]
@samselikoff looks good. 

@achambers Agreed adapters should be independent. Sam and I just talked about this a bit and we basically came to the conclusion that it's too hard to come up with a stable communication / interface for adapters to use. We'll provide an API where adapters can save some data, but I don't think we should encourage adapter-to-adapter communication. That said, if it's needed we can have an escape hatch and then look at why people are doing it and at that point provide a better API around it. I think for now I am going to punt on any sort of formal shared state api. @lukemelia thoughts?

**Comment by lukemelia** [comment]
I will review more thoroughly later but I'm agreed re: keeping shared state API minimal for now. with regard to all before*, *, after* hooks, do we have use cases for the before/after hooks, or can we keep it simpler?

**Comment by samselikoff** [comment]
I was thinking of didUpdate, didActivate etc. would be good hooks for like slack notifier adapters. They'd never need to know what was running in the #activate methods, they would just do stuff in the did* hooks. Just a thought though.

**Comment by LevelbossMike** [comment]
@samselikoff looks great!

These seem like 'to many' hooks but the idea is great. I suppose `willUpload`, 'didUpload' for adapters will be enough for the start and we can then provide more hooks if people need them.

**Comment by achambers** [comment]
Wasn't the **postDeploy** hook where notification type things would happen?

Feels a little like we might be pre-empting something that may or may not be needed with all the will* and did* hooks. 

This is something we can certainly do iteratively when the need arises no?

It'll be interesting to see how people start using it and make these decisions based on that.

**Comment by samselikoff** [comment]
- willDeploy
- build
- update
- activate
- didDeploy

Only thing that might be nice, hook into `willBuild` and `didBuild` for something like duration of build. Though for starters we could just log the time each step takes.

**Comment by achambers** [comment]
Cool.  My preference is to only add what we know we need to start with.  It's much easier to add a good feature than to remove a bad one ;)  That list looks good.

**Comment by joebartels** [comment]
I wonder if the hook `update` is too ambiguous.  If I'm reading the proposal correct, it sounds like `update` is where an addon is expected to upload assets. An update typically replaces something (e.g., one version for another). My concern is that uploading assets doesn't necessarily update or replace files.  Examples include: fingerprinted assets, uploading new files, relocating files.

On the other hand, `update` is a useful hook for actually updating/replacing the publicly accessible files, through swapping redis values, clearing cache on previous index.html, warming cache with new assets, etc.  `update` should be the task that actually updates your app to the public. *One thing to note is that in the case of no cache the `upload` hook may essentially act as an `update`.*

With that in mind, to me the most general deploy process looks like this and should accommodate using a hook multiple times. E.g., there may be 2 addons that utilize `upload` hook -one for *index.html*, another for */assets*
```
           /-- willBuild    confirm environment
          /
build --------> builds app assets, documentation, etc.
          \
           \-- didBuild     manipulate index.html, validate assets

           /-- willUpload   confirm remote servers(S3, Redis, Azure, etc.)
          /
upload -------> puts the assets somewhere(S3, Redis, Azure, Rackspace, etc.)
          \
           \-- didUpload    notify APIs (slack, pusher, etc.), warm cache

           /-- willUpdate   create backup of assets, notify APIs, uninstall earlier versions
          /
update -------> update earlier version with new version (clear cache, swap Redis values, etc.)
          \
           \-- didUpdate    notify APIs, warm cache
 
```
It's essentially 3 hooks (`build`, `upload`, `update`) and each hook has a corresponding "event" (which can be thought of as a hook) that is triggered before and after the main hook executes.

sorry to make this an even more opinionated thread but I really like the possibilities ember-cli-deploy provides and would love this tool to be simple and flexible to match 99% of web deploys. I think we agree the foundation is going to be the very crucial point for motivating utility through addons and usage through intuitiveness and flexibility

**Comment by lukemelia** [comment]
@joebartels excellent analysis and suggestions (and ASCII diagram). In your view, a team interested is interested in deploying assets to S3 and HTML to redis, they might have a plugin implementing the upload hook for assets, and a plugin implementing the upload and update hooks for HTML uploading and activating. Does that sound right?

**Comment by samselikoff** [comment]
@joebartels I believe the hooks your proposing are semantically equivalent to the original build-update-activate. Your concern is that the term "update" is suggestive of *replacing* assets, while many deploy processes won't actually do this.

When I originally wrote build-update-activate, I hadn't thought of this. To me, update meant, "put the assets somewhere." Actually, I think we started out with "upload", but I think we discussed some deploy scenarios where you don't actually "upload" anything - deploying your build to a local Dropbox folder, for instance. For these people, just moving their `dist` somwhere, perhaps on their own computer or a local network, I definitely still want them to be able to use ember-cli-deploy. 

So I definitely think we're all in agreement about the three stages:
 1. compile the app down to static files
 2. move the static files somewhere (upload over network to S3, send HTTP request to front_end_builds, upload to redis)
 3. notify the backend to use the new files

We're in agreement over `build` for step 1. I personally thing `activate` is less ambiguous for step 3. The question is, what's the best term for step 2? This is the hardest step to name, I think, because it's the most generic.

upload
update
distribute
install
upgrade

We could even alias it, so upload and update are synonymous for step 2.

**Comment by joebartels** [comment]
@lukemelia yeah exactly. having ember-cli-deploy support numerous 'build', or 'activate' addons would allow a developer to build their main app and build corresponding documentation (e.g., ember-cli-yuidoc) in the same deploy process using 2 addons that both utilize the 'build' hook. (*just to clarify, this isn't to say an addon will only utilize one hook*).

hearing the history of the naming, @samselikoff, definitely clarifies for me the purpose behind them. And  I don't feel as strongly against using 'update' hook to upload assets anymore. I think the heart of my confusion was the meaning of the words 'update' and 'activate' together -they don't contrast enough for me to understand their true purpose.

I still feel that being able to trigger a task before and after a hook executes could prove to be very useful. I also understand adding unnecessary bulk isn't on anyone's list of things to do. If that idea is still on the docket then I guess it has be decided whether `before` and `after` hooks are unnecessary

**Comment by samselikoff** [comment]
Makes sense. If we don't have before/after, we could also allow host app to specify order in which plugins run, if they need that much control

**Comment by Twinkletoes** [comment]
When designing this, we should be thinking of the "@lukemelia method" as a special case of a more generic deploy process.

The above discussion doesn't mention failure. What is the process if a plugin task fails - we could for example just call rollback on each plugin task and expect it to clean up its own mess.

**Comment by achambers** [comment]
@twinkletoes That's exactly the point of the pipeline. @lukemelia's method is just one way to deploy apps. We want to have a flexible pipeline that allows users to mix and match plugins to support their preferred deployment strategy. 

The point you raise about failure is a good one. That is not something we have really spoken about currently. Thanks for bringing it up.

**Comment by Twinkletoes** [comment]
My step naming would be:
1. build
2. deploy
3. configure (activate on redis, or set DNS routing, or create a cloudfront distribution)
4. notify

Each would have a will and did function.
Maybe we add rollback and commit too, one of which gets called as the final step.

For example if rollback requires restoring a backup then commit allows you to delete your backup

**Comment by Twinkletoes** [comment]
I'd like to see each service have a plugin, and the ordering be explicit - this allows the ability to have configurable steps.

e.g. I cannot set up a Route53 DNS alias to my Cloudfront distribution until that distribution is created. But these steps should be done by different configurable plugins.

If I have a B2B and B2C setup which only differ by branding then I may have to configure multiple Cloudfront distributions - if everything is automated to auto register plugins, how would I configure the deploy to run two configuration steps with different configs?

It feels to me as though there needs to be a script or a declarative file which sets the order of deployment steps. This would allow multiple copies of a single task, or conditional execution of steps, or pushing the output of one task into the input of another.

**Comment by Twinkletoes** [comment]
So I suppose that leaves the question: how should a development team use this shiny new stuff?

Should they plug together existing plugins which do the heavy lifting of working with various different service APIs, writing a config file that ties them all together (a la brocfile)?

Or should they write an addon which implements their specific build process, using the hooks provided by ember-cli-deploy?

For me the first of those options sounds
a) easier (and no harder in the case when your favourite service is not yet supported)
b) easier for newbies to get their head around

**Comment by samselikoff** [comment]
we're definitely going for the first option. s3 plugin should be generic enough for most people's use cases, etc.

**Comment by Twinkletoes** [comment]
in that case s3 plugin should have the following configuration:
aws credentials
bucket name
path prefix (e.g. put files in a subfolder in the bucket)

In a team development environment we should also be able to input the aws credentials (or any other service credentials) as environment variables, so that developers reading the script can't see your production credentials. Outsourced developers should not be able to have write access to s3! Only build servers should.

**Comment by LevelbossMike** [comment]
@Twinkletoes exactly. also all you specified in your last comment is already possible with the current release and `config/deploy.js` ;)

**Comment by Twinkletoes** [comment]
@LevelbossMike excellent

**Comment by Twinkletoes** [comment]
I'll be at the ember london project day on Sunday - anyone up for doing a spike on this together?

**Comment by dschmidt** [comment]
Question on deploy metadata:

Does this also mean there will be a proper format to read in after the process?
I have setup an IRC to do deployments for me, but for status reports I'm doing some really ugly string matching on the console output right now.

**Comment by lukemelia** [comment]
@dschmidt each pipeline plugin adds metadata to a "deploy" object that is available to subsequent pipeline plugins. So the idea is that we would have an ember-cli-deploy-irc plugin which implemented `didDeploy` and posted to IRC with information from the "deploy" object.

One potentially tricky thing about the open plugin system and deploy metadata approach is that we will need community conventions around what information is added to the "deploy" object. I think that this will evolve naturally, mostly driven by the core team's plugin implementations.

**Comment by dschmidt** [comment]
@lukemelia fair enough, might still be useful to serialize that object and dump it to a logfile, so it can be processed in CI e.g.  - could be in a plugin too of course

**Comment by lukemelia** [comment]
@dschmidt yep, perfect case for a simple plugin

**Comment by achambers** [comment]
+1 for the plugin approach for this.

**Comment by lukemelia** [comment]
Fun to read back through this on the cusp of 0.5.0!

Closing because these ideas are now in code!

**Comment by ghedamat** [comment]
:+1:
