### ISSUE TITLE
Update README to reflect move to ember-cli/ember-cli-deploy

### ISSUE THREAD

**Issue by achambers** [ember-cli/ember-cli-deploy#49]
Since moving `ember-deploy` to `ember-cli/ember-cli-deploy` we need to update the README.  It probably needs quite an overhaul but below are a few of the things mentioned in Slack.

- [ ] Change references to `ember-deploy` and LevelBossMike
- [ ] De-emphasise references to Luke's 'Lightening Deployments' presentation
- [ ] Add something to the top of the README to briefly explain the migration that has happened and why users of the former ember-cli-deploy will probably be experiencing issues.

**Comment by achambers** [comment]
Looking closer at the README, it seems it will likely need quite an overhaul.  There are a few unknowns at this stage as well such as how the API will actually look.  So I'm not sure how much detail we can add right away.

Is everyone happy with cutting it down to what we do currently know right now and then building from there as we go?

**Comment by lukemelia** [comment]
Sure, take a crack at it @achambers

**Comment by samselikoff** [comment]
@achambers did #59 close this?

**Comment by achambers** [comment]
@samselikoff It will close this yes.  But that PR is maybe a bit premature as it relates to the pipeline work which isn't nailed down right now obviously.  I think that PR will start to make more sense as we start building 0.5.0.

**Comment by lukemelia** [comment]
We've got docs!
