### ISSUE TITLE
Add blueprint to install starter deploy.js on install 

### ISSUE THREAD

**Issue by lukemelia** [ember-cli/ember-cli-deploy#52]
When ember-cli runs `ember install:addon ember-cli-deploy`, a blueprint should run to output a starter `config/deploy.js` file. The file should have some commented examples showing users how switch based on deploy environment, how to use environment variables, and execute a command synchronously to get a value.

**Comment by achambers** [comment]
Does it make sense for this to be in the 1.0.0 milestone @lukemelia ?

**Comment by lukemelia** [comment]
@achambers Yes, added

**Comment by achambers** [comment]
Cool, I'm on it.
