### ISSUE TITLE
Display extended revision information for ALL index adapters

### ISSUE THREAD

**Issue by quiddle** [ember-cli/ember-cli-deploy#61]
I wrote a [PR for ember-cli-deploy-s3-index](https://github.com/Kerry350/ember-deploy-s3-index/pull/4) that displays extended information when running `deploy:list` in a few ways:

1. If the `verbose` config value is set, it looks up the related git sha and displays the git log information.
2. It uses a `url` config value so the url to access a given revision can be generated and displayed next to the revision tag.
3. It added the ability to display which revision was currently active.

All of these things had to be done in the index-adapter, because ember-cli-deploy leaves the display of revisions up to the index adapter. There's some discussion [on the PR](https://github.com/Kerry350/ember-deploy-s3-index/pull/4) and also in [a separate issue](https://github.com/Kerry350/ember-deploy-s3-index/issues/5) about moving some of the intelligence into ember-cli-deploy.

In order to make these sort of changes work, we'd need to:

* move printing the list of revisions into ember-cli-deploy, and require the index-adapters to return a list/object of revisions, somehow marking which is `current`. (or responding to an additional method)
* Add a method to the taggingAdapters that respond with extended information, if available.

One of the other features I discussed was allowing `deploy:activate` to be called without arguments to activate the most recent revision or also to be called with just the number displayed next to the revision key.
```sh
$ ember deploy:list 
version: 0.1.15
Found the following revisions: 

1) my-app:5a77e50 
2) my-app:b8256de 
3) my-app:c239613  

Use activate() to activate one of these revisions

$ ember deploy:activate 
# would activate my-app:5a77e50

$ ember deploy:activate 2
# would activate  my-app:b8256de
```

I'm moving the discussion over here so we can figure out where some of these changes belong.

**Comment by lukemelia** [comment]
Really cool stuff here. A few thoughts:

1) We don't want to require git or require version identifiers to be git SHAs. See the discussion in #39 for more background. But it would be useful to be able to show that information if you are using git.
2) We're considering making a major breaking change to the plugin API (being discussed in #47) that would erase the strict concept of adapter types and instead allow ember-cli-deploy plugins to implement one or more of a set of hooks. We should consider these changes in that context, and also figure out what hooks need to exist to support this functionality.
3) the idea of activating the last uploaded version, or activating by # is a little scary because it is possible (albeit unlikely) for things to change between the time the list is generated and the time the subsequent command is run. Perhaps we should show the user the actual operation that will be done and prompt her for confirmation in those potentially dangerous usages?

**Comment by quiddle** [comment]
1. Sounds good. I struggled with how the tagging adapter story fit in when I was making those changes. The current setup in `ember-cli-deploy-s3-index` is hardcoded to the SHA tags, so I went with it. Perhaps when deploying a revision, a commit message could be included (maybe default to the most recent git commit log?). Which adapter would be responsible for managing those?
2. I'll stay on top of the conversation, looks like good stuff happening.
3. I like the idea of confirming the choice. How about if `deploy:activate` is run without arguments, the list is displayed and a prompt is given to select the revision (by number or by tag)? Then, even if someone else changes the deployed version while you're running, you'll still be selecting the correct revision tag. Then you can go figure out why so many people are deploying at once!

**Comment by quiddle** [comment]
Just for reference, the PR I made changes the `deploy:list` output to look like this:
![deploylistoutput](https://cloud.githubusercontent.com/assets/976237/6429326/d0e9ad96-bf97-11e4-9a80-0ca57cd3d908.png)

**Comment by lukemelia** [comment]
Nice output!

:+1: to the `deploy:activate` interaction you described.

I could see ember-cli-deploy providing this kind of git output if the objects returned from a  future `listVersions` hook included a `gitSha` property. Open question: how/where would the `gitSha` info be persisted? It does seems like providing it as information to the future `uploadIndex` hook would make sense, and then the plugin would be responsible for figuring out how to persist it and return it back later with the list of versions.

**Comment by LevelbossMike** [comment]
I like this output! Is there really a need to persist this information? I think just receiving and formatting it in the `listVersions` hook should be enough

**Comment by danshultz** [comment]
It would make sense that the tagging plugin would know how to retrieve this info as pulling this info depends how one manages the tagging. It would be up to the tagging plugin specified to store that information I would think.

List revisions would delegate to the tagging plugin to get the info.

I think that would be a good start and we could define a basic message interface so formatting is left up to the index plugin

**Comment by danshultz** [comment]
By, "that would be a good start" I mean, I think having the tagging adapter interrogate git currently and return a structure object as a message would be a good start since it generates the manifest tag.

Phone replying is hard  :)

**Comment by lukemelia** [comment]
@quiddle I'm going to close this as we've revamped everything for 0.5. That said, we really want to capture, store and display richer information in the 0.5 pipeline, and have some support for it already. If you're interested in helping out, let me know and we can help get your oriented to where the new code lives and what needs to happen.

**Comment by quiddle** [comment]
Thanks for the consideration! After I get things updated, I'll revisit the ideas I had here and consider a new pull request.
