### ISSUE TITLE
Work with plugin authors to get compatible with 0.4.0

### ISSUE THREAD

**Issue by lukemelia** [ember-cli/ember-cli-deploy#68]
### Existing Plugins

- [x] [ember-deploy-redis](https://github.com/LevelbossMike/ember-deploy-redis), index-adapter for [Redis](http://redis.io)
- [x] [ember-deploy-s3](https://github.com/LevelbossMike/ember-deploy-s3), assets-adapter for AWS [S3](http://aws.amazon.com/s3/)
- [x] [ember-deploy-s3-index](https://github.com/Kerry350/ember-deploy-s3-index), index-adapter for AWS [S3](http://aws.amazon.com/s3/)
- [ ] [ember-deploy-azure](https://github.com/duizendnegen/ember-deploy-azure), index-adapter and assets-adapter for Azure Tables & Blob Storage respectively

**Comment by LevelbossMike** [comment]
ember-deploy-redis and ember-deploy-s3 are already working with current master version.

**Comment by danshultz** [comment]
ember-deploy-s3-index will be working with current master after this PR lands https://github.com/Kerry350/ember-deploy-s3-index/pull/9

**Comment by duizendnegen** [comment]
will check compatibility one of the coming days

**Comment by achambers** [comment]
@duizendnegen Any update on this?  I'll be release v0.4.0 this weekend and would like io have confirmation before then if possible.

**Comment by lukemelia** [comment]
Closing this out for now to clear the way for 0.4.0. @duizendnegen get in touch if we can help with  ember-deploy-azure

**Comment by duizendnegen** [comment]
Sorry for the slow replies, has been resolved with help from @danshultz - thanks for that!
