### ISSUE TITLE
Upgrade instructions for users of achambers/ember-cli-deploy

### ISSUE THREAD

**Issue by lukemelia** [ember-cli/ember-cli-deploy#69]
- [ ]  Check for signs that the user might have been using the former ember-cli-deploy and warn them. (You can get a good idea by checking to see where the config is stored.)

**Comment by EmergentBehavior** [comment]
It would have been nice if this was done before the repository redirected. I saw in the old README that there would be an upgrade path, but recently when I reinstalled some node modules things broke. I imagine there may be other confused folks out there...

**Comment by achambers** [comment]
We haven't yet pushed anything to npm. What exactly broke mate?

**Comment by EmergentBehavior** [comment]
My bad, checked and was installing from git directly, so that explains it. Carry on... ;)
