### ISSUE TITLE
Document plugin architecture

### ISSUE THREAD

**Issue by achambers** [ember-cli/ember-cli-deploy#71]
Let's create a document that specifies the architecture decisions around plugins and how they should be developed.  This could be a markdown file in the root of the app, maybe called `DEVELOPING_PLUGINS.md` or `PLUGIN_ARCHITECTURE.md`.

A good place to get inspiration for this is [ember-cli/ADDON_HOOKS.md](https://github.com/ember-cli/ember-cli/blob/master/ADDON_HOOKS.md) and [ember-cli/ARCHITECTURE.md](https://github.com/ember-cli/ember-cli/blob/master/ARCHITECTURE.md)

**Comment by lukemelia** [comment]
This has now been well-documented on the docs site.
