### ISSUE TITLE
Support users upgrading from 0.0.6 to 0.4.0

### ISSUE THREAD

**Issue by danshultz** [ember-cli/ember-cli-deploy#75]
Users who are using version `0.0.6` will most likely get the upgrade of `0.4.0` automatically due to referencing  `^0.0.6`.

In order to prevent users from breaking when we publish `0.4.0`, the following issues would need to be addressed.

- [ ] Include an s3 plugin by default (this should only work or be registered if we detect someone using `preZeroFourZero`)
- [ ] Shim adapter loading to support the loading of https://github.com/achambers/ember-cli-deploy-redis-index-adapter
- [ ] Shim the config from `0.0.6` to support the old config structure
- [ ] Add feature detection based on config location (or other option?) to identify `preZeroFourZero` users
- [ ] ensure the following command flow works properly `ember build && ember deploy:index && ember deploy:assets && ember activate <version> && ember deploy:versions`

I think I've captured all the details here as a starting point for discussion. Please include any other thoughts and opinions on this.

**Comment by achambers** [comment]
Just added `ember deploy:versions` to the list of commands to support.

**Comment by lukemelia** [comment]
This all sounds good. My $.02 would just be that some level of breaking changes are acceptable for pre-1.0 projects, as both these are, so if any of these bullets are lots of work to solve elegantly and a small amount of work to give users upgrade instructions, that would be acceptable IMO.

**Comment by achambers** [comment]
That's a fair call. I guess we just need to work out where to draw the
line.

**Comment by lukemelia** [comment]
Exactly. Judgement call as you're moving through these bullets.

**Comment by lukemelia** [comment]
Closing this out in favor of warning message and migration docs in #85
