### ISSUE TITLE
.gitignore config/deploy.js by default?

### ISSUE THREAD

**Issue by brittanystoroz** [ember-cli/ember-cli-deploy#76]
Considering people may be storing sensitive credentials there. d06493324a690c5d95aab3e74f16f51a3c5cd21f

**Comment by achambers** [comment]
They should be using environment variables for emotive information. We need to commit the deploy.js config file. Think of ember-cli-deploy in a continuous integration scenario. The CI server will be deploying. Therefore the config needs to be present. 

If you're storing credentials in a config file, there are better ways.

**Comment by tofumatt** [comment]
Environment variables as in values set on a server (eg node, Rails, etc.)? What happens with an entirely client-side app? It's tough not to store config in a file when there is no "smart" server to talk with.

**Comment by achambers** [comment]
That client side app you talk about is built on a server, by ember-cli-deploy before the static assets are pushed somewhere. Are we talking about the same thing? I'm unclear as to what the problem is. This file is committed to git just like the ember-cli config/environment.js file is.

**Comment by brittanystoroz** [comment]
@achambers yea I actually just raised this issue because we're trying to implement something similar and I was looking for some patterns to follow =D But I'm realizing our use cases are a little different. We're trying to add a command that publishes a client-side app to the Firefox Marketplace. The endpoint requires authentication credentials which I wasn't sure where to put except for in a config file.

**Comment by achambers** [comment]
This config file is for deployment of an ember-CLI app only

**Comment by brittanystoroz** [comment]
Right our use case is for ember-cli apps as well (https://github.com/mozilla/ember-cli-fxos/pull/13) but realizing our use case is different...sorry about that! ~*this never happened*~

**Comment by achambers** [comment]
No probs ;)

**Comment by lukemelia** [comment]
Hi @brittanystoroz. I would love to learn more about what you're up to and whether the Firefox Marketplace submission could/should be implemented as ember-cli-deploy plugins. We're both here at #EmberConf

**Comment by danshultz** [comment]
@lukemelia @brittanystoroz :+1: to that. Looking at the commit you posted, I think this might reasonably plug into ember-cli-deploy and the pattern appears similar

**Comment by quiddle** [comment]
Keep in mind that you can use a ~/.aws/credentials file and avoid having to put your credentials into ANY of those files or set up environment variables. The aws-sdk has a variety of methods for supplying credentials. For scenarios like ember-cli-deploy, this guide applies- http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html

**Comment by brittanystoroz** [comment]
@lukemelia @danshultz yes let's chat! I'm speaking at 2ish tomorrow but any time after my talk we should find each other.

**Comment by achambers** [comment]
That's a good point about about AWS credentials.

Very interested to hear about the Mozilla deployment use case too.
