### ISSUE TITLE
Support for bucket name path

### ISSUE THREAD

**Issue by kcollignon** [ember-cli/ember-cli-deploy#84]
Unless my config option for the s3 `bucket` is a root bucket, i.e.- `assets` I get this error:

```ruby
Built project successfully. Stored in "dist/".
Uploading assets...
Unable to sync: NoSuchKey: The specified key does not exist.
```

I'd like to be able to pass a path to my bucket. i.e.-

```ruby
bucket: 'apps-assets/<my-app-name>/development'
```

**Comment by LevelbossMike** [comment]
You can use the `prefix` option for that. This is not well documented in `ember-deploy-s3` and I will update the README accordingly.

Basically you can pass any option that [node-s3-client](andrewrk/node-s3-client) supports to the s3-config. This is the library that is used by [ember-deploy-s3](levelbossmike/ember-deploy-s3) internally.

For now you can have a look at the documentation of the node-s3-client project to see what's available:
https://github.com/andrewrk/node-s3-client#sync-a-directory-to-s3

I will close this for now and create an issue in ember-deploy-s3. as this needs to improved there not in ember-cli-deploy.

**Comment by kcollignon** [comment]
Thanks @LevelbossMike !
