### ISSUE TITLE
Support index-adapters that rely on the asset-store

### ISSUE THREAD

**Issue by jamesarosen** [ember-cli/ember-cli-deploy#86]
### Background

I'm trying to develop an ember-cli-deploy activation add-on that works with pass-through caching layers like Varnish. Varnish, unlike Redis, has no way to actively insert `index.html`. Instead

 * `adapter.upload` uploads `index-295d1e4a.html` to the Assets server (e.g. S3)
 * `adapter.setCurrent` does three things:
   * overwrite a "symlink" object to the Assets server. This is an empty file called `current-version` that has an HTTP header like `X-Ember-Current-Version: 295d1e4a`
   * purges `/current-version` in Varnish
   * purges `/index.html` in Varnish

The next time someone requests `/index.html` from Varnish, it will make an upstream request to S3 for `/current-version`, parse the header, and turn the request for `/index.html` into one for `/index-295d1e4a.html`

Similarly, `listVersions` would ask the asset store for -- essentially -- `ls index-*.html`.

### Request

This sort of workflow relies on three changes to the current API:

 1. Inject the asset uploader into the index adapter
 2. Asset stores have a public API to upload single file
 3. Asset stores have a public API to list files

That feels like a *lot* to change in the current ecosystem. The only alternatives I see are

 1. `ember-cli-deploy-varnish` index-adapter understands *all* of the various ways of storing assets
 2. `ember-cli-deploy-varnish` index-adapter requires the client application to configure complex upload and query operations

Does anyone else have other suggestions?

**Comment by lukemelia** [comment]
Change 1 will be addressed by the elimination of adapter types in favor of plugins implementing 1 or more hooks. This is planned for 0.5.0 and your needs are a great example of why.

Changes 2 & 3 would be addressed how your plugin implements the `uploadIndex`, `activate`, and `getVersions` hooks. (naming of these hooks is still WIP).

Seems pretty straightforward for 0.5.0. Other members of @ember-cli/ember-deploy have thoughts?

**Comment by samselikoff** [comment]
I agree, our front_end_builds implementation does something similar, where the backend fetches `index` from S3. 0.5.0 should handle this.

**Comment by jamesarosen** [comment]
@lukemelia @samselikoff if I'm reading you right, then there will be some new hooks needed:

 * `uploadAsset` (singular), which doesn't do the `build` phase. `ember-cli-deploy-varnish` will call this twice from `uploadIndex`
 * `listAssets`

**Comment by samselikoff** [comment]
Your adapter could implement a completely custom pipeline, bypassing defaults such as `ember build` during build phase.

Current defaults are something like 

```js
export default {
  build: function() {
    // run ember build --environment production
  },

  updateAssets: function() {
    // upload js/css to os3
  },

  updateIndex: function() {
    // upload index to redis
  }
```

You could write something completely custom

```js
export default {
  deploy: function() {
    // all your logic here
  }
}
```

while still in the future being able to add things like `ember-cli-deploy-slack-notifier` that hooks into `afterDeploy` hook.

**Comment by jamesarosen** [comment]
But what I'm saying is that I want my plugin to be agnostic about where the assets are stored. I don't want to write `ember-cli-deploy-varnish-and-s3` and `ember-cli-deploy-varnish-and-gcs` and `ember-cli-deploy-varnish-and-sftp`.

**Comment by samselikoff** [comment]
We have discussed this a bit. Cross-plugin communication is a pandora's box, and I think we want to be a little more hands-off to start before we come up with some conventions around the state that will be shared.

We will probably have a mechanism for the host app to interact with data return from plugins, but we're still thinking this through. 

Rest assured this is a use case for us too, so we'll be thinking about it. The first solution may not be completely automated - your `ember-cli-deploy-varnish` plugin may list which asset plugins it supports, then have to do some checking internally (for each plugin you wish to support).

**Comment by lukemelia** [comment]
@jamesarosen @samselikoff yes, the composability question is interesting. We're going to have to noodle on this some more.

**Comment by jamesarosen** [comment]
It wouldn't be unreasonable for the configuration for `ember-cli-deploy-varnish` to include a path that it imports to get access to `uploadAsset` and `listAssets`. The library could ship with `ember-cli-deploy-varnish/lib/scp-storage.js` as an example. Then other storage-centric adapters could simply expose a module that has those functions if they want to be compatible with `ember-cli-deploy-varnish`.

**Comment by samselikoff** [comment]
<thinking-out-loud>
I think in the beginning, it would be `ember-cli-deploy-varnish`'s responsibility to support the various asset adapters (the same way it's `front_end_builds`'s responsibility). deploy-varnish is a deploy solution that works with [s3]. The goal here is that you could lighten your plugin's workload by taking advantage of an s3 adapter that already works. So, you could say expose a config to your plugin's users that says `uploadAssetsTo` that could be one of `s3`, `gcs`, etc. , and your plugin could use an existing `s3` plugin to do the s3 dirty work.

I don't think there's enough of a uniform interface yet across the different deploy models to say, "any plugin that uploads assets should return the assets location under this key". I think instead, we may start with, "any plugin can return any arbitrary data, that host apps/other plugins can read from". So initially, if you wanted your varnish plugin to use `ember-cli-deploy-s3`, you'd simply have to read those docs and have some branch of your code read the correct data from its return value.

As the ecosystem develops these abstractions may crystalize, and then we could build more state into `ember-cli-deploy` itself. But my thinking is initially, `ember-cli-deploy` is going to remain very dumb about all this.
</thinking-out-loud>

**Comment by Twinkletoes** [comment]
what if a plugin only had to implement deploy?

My deploy pipline uploads everything to a branch folder on S3 (each branch in its own folder), then sets up a cloudfront cache on the front if one doesn't exist already, and creates branchname.domain.com DNS entries on Route53. 

Most of these steps are not deploying files - I'd like to be able to create open source plugins that update cloudfront, or inject a dns entry.

It feels like a deploy process is a list of steps, each of which might fail, or might return a data object. Maybe a deploy pipeline is a list of plugins, each with a config object, perhaps with a function determining whether they get run, that can read from the previous step plugins either their success status or something from their data. Perhaps the config can include fields bound from the data output of previous named steps.

**Comment by LevelbossMike** [comment]
Hi @Twinkletoes!

Thanks for your participation! It sounds like the use-case you are describing can be solved by the upcoming deploy-pipeline hook architecture that is currently planned for the upcoming releases:

https://github.com/ember-cli/ember-cli-deploy/blob/rfc_plugin_arch/rfc/plugins.md#plugins

Please let us know in https://github.com/ember-cli/ember-cli-deploy/pull/88 what your thoughts on our currently planned approach are and add everything you think is relevant.

What you describe should definitely be supported by ember-cli-deploy and we plan on delivering exactly that with the deployment-pipeline/plugin-architecture described in https://github.com/ember-cli/ember-cli-deploy/pull/88

**Comment by LevelbossMike** [comment]
@Twinkletoes here's another issue with details about the idea of the deployment pipeline https://github.com/ember-cli/ember-cli-deploy/issues/47

**Comment by lukemelia** [comment]
This is now quite doable with the 0.5.x plugin model.

**Comment by BryanCrotaz** [comment]
it sounds excellent - about to use it for realz. in a project we're kicking off next week. Some of which is deploying to AWS Lambda. Hoping to use ember-deploy for front end and back end together.

**Comment by lukemelia** [comment]
@BryanCrotaz awesome. let us know how it goes!
