### ISSUE TITLE
Support "Configuration-Only" Deploy

### ISSUE THREAD

**Issue by blimmer** [ember-cli/ember-cli-deploy#89]
It would be really great if ember-cli-deploy supported different deploy types, other than just deploying the index.html file. 

For most apps, there are usually three things that change in the index.html file between deploys. For my app, it's
```
app-<hash>.js
app-<hash>.css
vendor-<hash>.js
```
And the rest of the index.html page always stays the same.

### Use Case
We insert dynamic content into our index.html on each request. For instance, we use [node-geoip](https://github.com/bluesmoon/node-geoip) to make a best guess at the user's location and insert it into the rendered index.html for Ember to read out. You can imagine other cases where one might want to modify the HTML before serving to the user (user specific api token, etc.)

With the current implementation, we have to deploy the entire index.html file with a marker (like an HTML comment) to know where to insert our dynamic content.
```html
<head>
  ...
  <link rel="stylesheet" href="//app-abc1234.css">
  <!-- Insert server data below -->
</head>
```
Then we have to locate this comment, remove it and insert our data.

### Feature Request
It would be great if ember-cli-deploy could be configured such that Redis could store just the hashes of the files that change between deploys. This way, we could leave the construction of the (very) simple index.html file to the server and more easily control where we insert our dynamic server data.

**Comment by achambers** [comment]
Hi Ben,

Thanks for the suggestion. That's an interesting use case. The plan for
ember-CLI-deploy is to allow custom plugins to plug in to the deploy
pipeline so you can customise the process just like this.

There is talking of a plugin that sends the index information as json
instead of html allowing servers to use their own templating which may also
work for you in this case.

Anyway, v0.5.0 should start to have some of the pipeline functionality so
hopefully we will be able to provide you the flexibility to suit your use
case soon.

Would love to hear more about your use case as well.

Thanks again for the suggestion.

**Comment by blimmer** [comment]
Thanks for the quick response, Aaron. It definitely sounds like the custom plugin work could yield something that we could use to create a plugin to do this. I filed this issue after chatting with @lukemelia at EmberConf about this. He talked about the possibility of integrating this kind of functionality with ember-cli-deploy.

Also, the json vs. html would be much easier than what we're considering doing now. The biggest problem is that with html we have to use a library to parse, find the comment and insert the information. It's far easier to parse something like JSON vs. HTML on the server.

Currently we're inserting a few different things server-side:
+ API token  
   We have a method server-side to generate a token that Ember Data attaches to each API request.
+ Location  
   My app's content varies by physical location. We run the request IP address through a geocoder to make a best guess on the user's location and embed in index.html. Think something like Groupon or LivingSocial that needs to show you deals in your area.
+ New Relic  
   We also use node-newrelic to insert [browser timing headers](https://github.com/newrelic/node-newrelic#browser-timings-rum--real-user-monitoring) for each request.

As a possible solution, I was thinking that instead of just a key-value we could use a Redis `HSET` for this case. So you could have something like this:

```
HGETALL current
1) "appHash"
2) "def123"
3) "cssHash"
4) "ghi123"
```

**Comment by LevelbossMike** [comment]
In one of the projects I worked one we had the same needs. We fetched the index.html from redis and injected properties like api-token, locale (by IP or user specified locale) etc. server-side before serving the index.html

I don't think json is a good idea in this case because it complicates things a lot and your usecase is already supported with the current implementation. You'd also need to support some kind of JSON-build in ember-cli directly (ember-cli-deploy does not do anything special it just uses the build task from ember-cli). What would be useful though is a better support for placeholders that can be filled out by a server-implementation. Maybe the fast-boot server or the server that is responsible for serving your fast-bootable index.html could fill out the dynamic content before serving html to your users. If this worked the build process could stay the same and the rest of the deployment-pipeline also.

Did you run into problems with the current way of injecting stuff into index.html?

**Comment by lukemelia** [comment]
In my experience working with consulting clients, companies are often averse to shipping HTML around, especially when they want their server-side app to be primarily responsible for the shell of the HTML on the page. Also, rewriting the URI-encoded JSON config meta tag can be somewhat annoying if you need to do that. In these situations, outputting JSON from the build makes sense.

JSON build output should be implemented as a separate addon, but I would be in favor of a future version of ember-cli-deploy having the right hooks to make working with this easy. I would suspect it will just be a matter of deploying json where we are normally deploying HTML.

**Comment by blimmer** [comment]
@LevelbossMike sounds like on that previous project you had very similar needs to what we need to do. You caught me a little, we haven't yet moved to Ember CLI (I hope to do this in the coming weeks) so my "current solution" is just in my head, but I'm pretty confident it will work. How did you inject your properties. I was looking at [cheerio](https://github.com/cheeriojs/cheerio) and it looks like it could work with the current ember-cli-deploy feature set.

@lukemelia I tend to agree with your consulting clients regarding shipping HTML around. Since the index.html page rarely changes in a meaningful way, I lean towards using a JSON "configuration" deploy. I guess the biggest problem is that it couples the deploys in the case where index.html and the client side changes **must** go out together (which, in my experience, isn't often).

I would definitely be OK with JSON output as a plugin, and I (briefly) looked into the hooks and I didn't see exactly how we would implement this sort of plugin. Perhaps this issue should track which hooks would be needed?

**Comment by LevelbossMike** [comment]
@blimmer We did not use cheerio because the server that was responsible for serving the index.html was written in Ruby (a Rails application). We just put ne necessary parts into meta tags which we then parsed on application start of our ember app.

This of course is kind of messy but it worked fine for our use-case.

**Comment by blimmer** [comment]
Did you use a similar library to manipulate (insert the `meta` tags) on the HTML string you got back?

**Comment by LevelbossMike** [comment]
If I remember correctly we just manipulated the html string directly but I see nothing wrong with using a library to do that.

**Comment by lukemelia** [comment]
@blimmer if you wanted to help out on the OSS side, I think creating an addon that adds json output to ember-cli's build would be great. Maybe called "ember-cli-json-output"? Figuring out the right hooks might be challenging, but I'm pretty confident this is doable.

**Comment by blimmer** [comment]
Depending on how quickly I need to get my app over to CLI and deployed, I might have time to work on the OSS solution to this problem. 

From a high level, this is how I see something like this working:
* The user configures the add on telling it what specific files or file types they went to upload to their db of choice. They could provide things like `*.js`, `*.css`, `*.extension` or `app-*.js`, `app-*.extension`.
* The addon (recursively?) navigates through the `dist/` folder created by `ember build`, and notes the files matching the configuration params.
* Instead of an index.html file, the addon produces a JSON block that you will upload to your DB, something like:
```
{
  "js": [
    "app-abc123.js",
    "vendor-def456.js"
  ],
  "css": [
    "app-abc789.css",
    "vendor-abc123.css"
  ],
  "extension": [
    "some-random-file.extension"  
  ]
}
```

* The adapter would store this JSON block in lieu of the index.html (keyed by the revision number as it is today). I believe this means that the index adapters could be useful wholesale.
* The asset upload would not need to be customized because we still want to upload our same assets to S3 or another store
Does this high-level plan make sense?

Outstanding question:
* It seems like [deploy-index.js](https://github.com/ember-cli/ember-cli-deploy/blob/master/lib/tasks/deploy-index.js#L44) is coupled to reading the contents of `dist/index.html`. It passes the HTML-string directly to the `upload` function on the index-adapter. How should this behavior be modified to do something different?

Thanks for your time and help with this idea!

**Comment by LevelbossMike** [comment]
you could just ignore the passed index.html file and do your own thing in the upload function of the index-adapter for now but we will think about a way how to better customize the steps for the 0.5.0 release.

**Comment by blimmer** [comment]
Sounds good. I'll do a quick prototype to see what I can get going. If 0.5.0 isn't released by the time we need to go live, we can do it the way you suggested (ignoring index.html from `upload()`). Should we leave this issue open for consideration on a potential supporting change in 0.5.0?

**Comment by lukemelia** [comment]
Yep. I'm going to tag this `plugin-use-case` and for 0.5.0.

**Comment by samselikoff** [comment]
I definitely think the default should still be index.html, since everyone is familiar with that and that's what everyone expects, though we've done something similar (string parse to insert meta tags). A plugin that pushes updated JSON seems very reasonable.

**Comment by blimmer** [comment]
In case anyone else is going the `meta` tag configuration route, I just open-sourced the plugin I wrote to handle meta tag configurations on the App-side. It's called [ember-cli-server-variables](https://github.com/blimmer/ember-cli-server-variables). It's pretty basic, but is working for our current use case.

**Comment by knownasilya** [comment]
This is probably one of the reasons that we don't currently use ember-cli-deploy (along with the overhead of needing redis for every app and having a separate deploy for server side).

**Comment by lukemelia** [comment]
With 0.5.0, we now have https://github.com/ember-cli-deploy/ember-cli-deploy-json-config and @achambers is already using it to deploy a production app.
