### ISSUE TITLE
Dependency execSync for win64 requires rebuilding with node-gyp

### ISSUE THREAD

**Issue by duizendnegen** [ember-cli/ember-cli-deploy#92]
solved as described in https://github.com/mgutz/execSync/issues/24#issuecomment-59258561 - But only after installation, for that installation instance only. This is also affecting `ember-cli-deploy` for Windows

as I think I'm one of the few (the only?) contributor here with Windows, I'll try and take ownership of this as well - just posting this issue to have something to refer to / some discussion points

`execSync` is used for executing git tagging only - before `ember-deploy` had a dependency on `gitty` (iirc) (which was also problematic under Windows). So, maybe
- consider alternative ways for getting the git version tag
- consider alternatives to `execSync` (for example `sync-exec`)
- use io.js and node.js v0.12 execSync

Most likely we can do some 0.12+ detection, then otherwise require sync-exec.

**Comment by joebartels** [comment]
hey @duizendnegen if you have time to quickly test a branch where `sync-exec` is used as replacement that'd be awesome. It'll at least see if exploring `sync-exec` is viable solution:
https://github.com/joebartels/ember-cli-deploy/tree/swap_sync_exec

a similar concern was brought up regards to `execSync` in https://github.com/ember-cli/ember-cli-deploy/issues/90

**Comment by duizendnegen** [comment]
That's great @joebartels! Should merge that, that solves my issues. It even has a pass-through for node.js >= 0.12, using the native call.

**Comment by joebartels** [comment]
Thanks for giving it a try. Glad it worked. Put a PR in so hopefully it'll get merged or the attn. needed for a  solution to get into master. https://github.com/ember-cli/ember-cli-deploy/pull/93
