### ISSUE TITLE
Problem accessing assets after deploying

### ISSUE THREAD

**Issue by seifsallam** [ember-cli/ember-cli-deploy#98]
I'm using node.js setup from [here](https://github.com/philipheinser/ember-lightning) with S3. But the uploaded `index.html` doesn't update URLs to use S3 full URL, instead it uses relative URL which doesn't exist. Am I missing something?

**Comment by LevelbossMike** [comment]
You need to setup the `fingerprint.prepend`-option correctly before deploying to production. This makes sure your assets are reference correctly in index.html. You can have a look at the [readme](https://github.com/ember-cli/ember-cli-deploy#fingerprinting-options--staging-environments) how to do this correctly.

**Comment by LevelbossMike** [comment]
Please feel free to reopen if this does not solve your problem. We just want to make sure we keep the issues up to date.

**Comment by seifsallam** [comment]
It worked. Thanks a lot :)
